import { CombatAchievementTask, CombatAchievementTier } from '../CombatAchievement';

export enum CombatAchievementTaskType {
  KillCount = 'Kill Count',
  Restriction = 'Restriction',
  Mechanical = 'Mechanical',
  Perfection = 'Perfection',
}

/**
 * Easy-tier Combat Achievement tasks, authored directly in TypeScript.
 *
 * Source: https://oldschool.runescape.wiki/w/Combat_Achievements/Easy
 */
export const EASY_COMBAT_ACHIEVEMENTS: CombatAchievementTask[] = [
  {
    description: 'Kill an Aberrant Spectre.',
    id: 0,
    monster: 'Aberrant Spectre',
    name: 'Noxious Foe',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Open the Barrows chest 10 times.',
    id: 24,
    monster: 'Barrows',
    name: 'Barrows Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill any Barrows Brother using only magical damage.',
    id: 28,
    monster: 'Barrows',
    name: 'Defence? What Defence?',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.Restriction,
  },
  {
    description: 'Kill a Black Dragon.',
    id: 32,
    monster: 'Black Dragon',
    name: 'Big, Black and Fiery',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill a Bloodveld.',
    id: 33,
    monster: 'Bloodveld',
    name: 'The Demonic Punching Bag',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: "Open Bryophyta's chest once.",
    id: 35,
    monster: 'Bryophyta',
    name: 'Bryophyta Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill Bryophyta with the Protect from Magic prayer active.',
    id: 37,
    monster: 'Bryophyta',
    name: 'Protection from Moss',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Kill Bryophyta without suffering any poison damage.',
    id: 39,
    monster: 'Bryophyta',
    name: 'Preparation Is Key',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.Perfection,
  },
  {
    description: 'Kill Bryophyta with either poison or venom being the final source of damage.',
    id: 40,
    monster: 'Bryophyta',
    name: 'A Slow Death',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill Bryophyta on a free to play world.',
    id: 41,
    monster: 'Bryophyta',
    name: 'Fighting as Intended II',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill the Deranged Archaeologist 10 times.',
    id: 76,
    monster: 'Deranged Archaeologist',
    name: 'Deranged Archaeologist Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill a Fire Giant.',
    id: 80,
    monster: 'Fire Giant',
    name: 'The Walking Volcano',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill a Greater Demon.',
    id: 120,
    monster: 'Greater Demon',
    name: 'A Greater Foe',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Finish off a Greater Demon with a demonbane weapon.',
    id: 121,
    monster: 'Greater Demon',
    name: 'Not So Great After All',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill a Hellhound.',
    id: 122,
    monster: 'Hellhound',
    name: "A Demon's Best Friend",
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: "Open Obor's chest once.",
    id: 129,
    monster: 'Obor',
    name: 'Obor Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill Obor whilst he is immobilized.',
    id: 131,
    monster: 'Obor',
    name: 'Sleeping Giant',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Kill Obor on a free to play world.',
    id: 134,
    monster: 'Obor',
    name: 'Fighting as Intended',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill the King Black Dragon 10 times.',
    id: 162,
    monster: 'King Black Dragon',
    name: 'King Black Dragon Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill a Lizardman Shaman.',
    id: 174,
    monster: 'Lizardman Shaman',
    name: 'A Scaley Encounter',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill a Lizardman Shaman in Molch which has not dealt damage to anyone (excluding its Spawns).',
    id: 175,
    monster: 'Lizardman Shaman',
    name: 'Shayzien Protector',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.Perfection,
  },
  {
    description: 'Kill the Giant Mole 10 times.',
    id: 177,
    monster: 'Giant Mole',
    name: 'Giant Mole Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill Sarachnis 10 times.',
    id: 206,
    monster: 'Sarachnis',
    name: 'Sarachnis Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Subdue the Wintertodt 5 times.',
    id: 279,
    monster: 'Wintertodt',
    name: 'Wintertodt Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Heal a pyromancer after they have fallen.',
    id: 281,
    monster: 'Wintertodt',
    name: 'Mummy!',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Repair a brazier which has been destroyed by the Wintertodt.',
    id: 282,
    monster: 'Wintertodt',
    name: 'Handyman',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Subdue the Wintertodt with four pieces of warm equipment equipped.',
    id: 285,
    monster: 'Wintertodt',
    name: 'Cosy',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill a Wyrm.',
    id: 287,
    monster: 'Wyrm',
    name: 'A Slithery Encounter',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Subdue Tempoross 5 times.',
    id: 353,
    monster: 'Tempoross',
    name: 'Tempoross Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Extinguish at least 5 fires during a single Tempoross fight.',
    id: 356,
    monster: 'Tempoross',
    name: 'Master of Buckets',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Repair either a mast or a totem pole.',
    id: 357,
    monster: 'Tempoross',
    name: 'Calm Before the Storm',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Attack Tempoross from both sides by loading both cannons on both ships.',
    id: 360,
    monster: 'Tempoross',
    name: 'Fire in the Hole!',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Kill a Hill Giant, Moss Giant and Fire Giant in the Giant Cave within the Shayzien region.',
    id: 398,
    monster: 'Giants',
    name: 'Into the Den of Giants',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill Scurrius once.',
    id: 521,
    monster: 'Scurrius',
    name: 'Scurrius Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Finish off Scurrius with a ratbane weapon in a private instance.',
    id: 523,
    monster: 'Scurrius',
    name: 'Sit Rat',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill one Titan at a time, without attacking the other.',
    id: 591,
    monster: 'Royal Titans',
    name: 'One by one',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill the Royal Titans without attacking any elementals.',
    id: 594,
    monster: 'Royal Titans',
    name: 'Elemental Company',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill the Royal Titans while having the Royal Titans kill a total of 10 elementals.',
    id: 597,
    monster: 'Royal Titans',
    name: 'Let them fight',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Restriction',
  },
  {
    description: 'Kill the Shellbane Gryphon 25 times.',
    id: 625,
    monster: 'Shellbane gryphon',
    name: 'Shellbane Adept',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
  {
    description: 'Kill the Shellbane Gryphon after clearing its corrosive spit from your armour.',
    id: 630,
    monster: 'Shellbane gryphon',
    name: 'Dry Cleaning',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: 'Mechanical',
  },
  {
    description: 'Kill Brutus.',
    id: 632,
    monster: 'Brutus',
    name: 'Brutus Novice',
    points: 1,
    tier: CombatAchievementTier.Easy,
    type: CombatAchievementTaskType.KillCount,
  },
];
