import { CombatAchievementTask, CombatAchievementTier } from '../CombatAchievement';

/**
 * Elite-tier Combat Achievement tasks, authored directly in TypeScript.
 *
 * Source: https://oldschool.runescape.wiki/w/Combat_Achievements/Elite
 */
export const ELITE_COMBAT_ACHIEVEMENTS: CombatAchievementTask[] = [
  {
    description: 'Kill the Abyssal Sire 50 times.',
    id: 2,
    monster: 'Abyssal Sire',
    name: 'Abyssal Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Abyssal Sire after only stunning him once.',
    id: 4,
    monster: 'Abyssal Sire',
    name: 'Respiratory Runner',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: "Use the Vengeance spell to reflect the damage from the Abyssal Sire's explosion back to him.",
    id: 6,
    monster: 'Abyssal Sire',
    name: 'Demonic Rebound',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Kill the Abyssal Sire without taking damage from the external tentacles, miasma pools, explosion or damage from the Abyssal Sire without praying the appropriate protection prayer.',
    id: 8,
    monster: 'Abyssal Sire',
    name: 'Perfect Sire',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: "Kill Kree'arra 100 times.",
    id: 10,
    monster: "Kree'arra",
    name: "Kree'arra Veteran",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill General Graardor 100 times.',
    id: 17,
    monster: 'General Graardor',
    name: 'General Graardor Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill General Graardor without him attacking any players.',
    id: 19,
    monster: 'General Graardor',
    name: 'Ourg Freezer II',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill a Basilisk Knight.',
    id: 31,
    monster: 'Basilisk Knight',
    name: 'Reflecting on This Encounter',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Callisto 20 times.',
    id: 43,
    monster: 'Callisto',
    name: 'Callisto Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Skotizo without taking any damage.',
    id: 47,
    monster: 'Skotizo',
    name: 'Demon Evasion',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill Skotizo without equipping a demonbane weapon.',
    id: 49,
    monster: 'Skotizo',
    name: 'Up for the Challenge',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Cerberus 75 times.',
    id: 51,
    monster: 'Cerberus',
    name: 'Cerberus Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Cerberus after successfully negating 6 or more attacks from Summoned Souls.',
    id: 54,
    monster: 'Cerberus',
    name: 'Ghost Buster',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Cerberus without taking damage from any lava pools.',
    id: 55,
    monster: 'Cerberus',
    name: 'Unrequired Antifire',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill Cerberus without taking any melee damage.',
    id: 56,
    monster: 'Cerberus',
    name: 'Anti-Bite Mechanics',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill the Chaos Elemental 25 times.',
    id: 58,
    monster: 'Chaos Elemental',
    name: 'Chaos Elemental Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Corporeal Beast 25 times.',
    id: 65,
    monster: 'Corporeal Beast',
    name: 'Corporeal Beast Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Corporeal Beast without anyone killing the dark core or taking damage from the dark core.',
    id: 67,
    monster: 'Corporeal Beast',
    name: 'Hot on Your Feet',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Finish off the Corporeal Beast with a Halberd special attack.',
    id: 68,
    monster: 'Corporeal Beast',
    name: 'Finding the Weak Spot',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Corporeal Beast solo.',
    id: 69,
    monster: 'Corporeal Beast',
    name: 'Chicken Killer',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill a Demonic Gorilla.',
    id: 74,
    monster: 'Demonic Gorilla',
    name: 'If Gorillas Could Fly',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Finish off a Demonic Gorilla with a demonbane weapon.',
    id: 75,
    monster: 'Demonic Gorilla',
    name: 'Hitting Them Where It Hurts',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Galvek in less than 3 minutes.',
    id: 81,
    monster: 'Galvek',
    name: 'Galvek Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill the Grotesque Guardians 50 times.',
    id: 83,
    monster: 'Grotesque Guardians',
    name: 'Grotesque Guardians Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Grotesque Guardians before Dusk uses his prison attack for a second time.',
    id: 89,
    monster: 'Grotesque Guardians',
    name: 'Done before Dusk',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Kill the Grotesque Guardians whilst completing the "Don\'t look at the eclipse", "Prison Break", "Granite Footwork", "Heal no more", "Static Awareness" and "Done before dusk" tasks.',
    id: 90,
    monster: 'Grotesque Guardians',
    name: 'Perfect Grotesque Guardians',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill the Grotesque Guardians in less than 2 minutes.',
    id: 92,
    monster: 'Grotesque Guardians',
    name: 'Grotesque Guardians Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill the Grotesque Guardians 10 times without leaving the instance.',
    id: 95,
    monster: 'Grotesque Guardians',
    name: 'From Dusk...',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Stamina',
  },
  {
    description: 'Complete the Corrupted Gauntlet 5 times.',
    id: 98,
    monster: 'Corrupted Hunllef',
    name: 'Corrupted Gauntlet Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Corrupted Hunllef without taking damage off prayer.',
    id: 101,
    monster: 'Corrupted Hunllef',
    name: '3, 2, 1 - Mage',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Complete the Gauntlet 5 times.',
    id: 109,
    monster: 'Crystalline Hunllef',
    name: 'Gauntlet Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Crystalline Hunllef without taking damage off prayer.',
    id: 111,
    monster: 'Crystalline Hunllef',
    name: '3, 2, 1 - Range',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill the Crystalline Hunllef without making an egniol potion within the Gauntlet.',
    id: 114,
    monster: 'Crystalline Hunllef',
    name: 'Egniol Diet',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Crystalline Hunllef with a full set of perfected armour equipped.',
    id: 115,
    monster: 'Crystalline Hunllef',
    name: 'Crystalline Warrior',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Crystalline Hunllef without making more than one attuned weapon.',
    id: 116,
    monster: 'Crystalline Hunllef',
    name: 'Wolf Puncher',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Glough in less than 2 minutes and 30 seconds.',
    id: 119,
    monster: 'Glough',
    name: 'Glough Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Hespori without losing any prayer points.',
    id: 126,
    monster: 'Hespori',
    name: 'Plant-Based Diet',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Hespori in less than 48 seconds.',
    id: 127,
    monster: 'Hespori',
    name: 'Hespori Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill the Alchemical Hydra 75 times.',
    id: 135,
    monster: 'Alchemical Hydra',
    name: 'Alchemical Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Fight Caves once.',
    id: 147,
    monster: 'TzTok-Jad',
    name: 'Fight Caves Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Fight Caves after surviving a hit from TzTok-Jad without praying.',
    id: 149,
    monster: 'TzTok-Jad',
    name: 'A Near Miss!',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Fight Caves with only melee.',
    id: 153,
    monster: 'TzTok-Jad',
    name: 'Facing Jad Head-on',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Kalphite Queen 50 times.',
    id: 158,
    monster: 'Kalphite Queen',
    name: 'Kalphite Queen Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Kalphite Queen by using the Vengeance spell as the finishing blow.',
    id: 160,
    monster: 'Kalphite Queen',
    name: 'Insect Deflection',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: "Kill the Kalphite Queen using only the Verac's Flail as a weapon.",
    id: 161,
    monster: 'Kalphite Queen',
    name: 'Prayer Smasher',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Kraken 50 times in a private instance without leaving the room.',
    id: 171,
    monster: 'Kraken',
    name: 'Ten-tacles',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Stamina',
  },
  {
    description: 'Kill the Mimic once.',
    id: 176,
    monster: 'The Mimic',
    name: 'Mimic Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Giant Mole with 4 or fewer instances of damage.',
    id: 180,
    monster: 'Giant Mole',
    name: 'Hard Hitter',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill The Nightmare 25 times.',
    id: 184,
    monster: 'The Nightmare',
    name: 'Nightmare Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill two Husks at the same time.',
    id: 187,
    monster: 'The Nightmare',
    name: 'Explosion!',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Nightmare solo.',
    id: 189,
    monster: 'The Nightmare',
    name: 'Sleep Tight',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Defeat the Nightmare (Solo) in less than 23 minutes.',
    id: 191,
    monster: 'The Nightmare',
    name: 'Nightmare (Solo) Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Defeat the Nightmare (5-scale) in less than 5 minutes.',
    id: 194,
    monster: 'The Nightmare',
    name: 'Nightmare (5-Scale) Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Dagannoth Prime whilst under attack by Dagannoth Supreme and Dagannoth Rex.',
    id: 199,
    monster: 'Dagannoth Prime',
    name: 'Death to the Seer King',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Prime using a Rune Thrownaxe special attack, bounced off Dagannoth Rex.',
    id: 200,
    monster: 'Dagannoth Prime',
    name: 'From One King to Another',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Dagannoth Rex whilst under attack by Dagannoth Supreme and Dagannoth Prime.',
    id: 203,
    monster: 'Dagannoth Rex',
    name: 'Death to the Warrior King',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Dagannoth Rex and one other Dagannoth king at the exact same time.',
    id: 205,
    monster: 'Dagannoth Rex',
    name: 'Toppling the Diarchy',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Commander Zilyana 100 times.',
    id: 212,
    monster: 'Commander Zilyana',
    name: 'Commander Zilyana Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Commander Zilyana in a private instance with melee only.',
    id: 216,
    monster: 'Commander Zilyana',
    name: 'Reminisce',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Scorpia 25 times.',
    id: 219,
    monster: 'Scorpia',
    name: 'Scorpia Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill The Fragment of Seren in less than 4 minutes.',
    id: 222,
    monster: 'Fragment of Seren',
    name: 'Fragment of Seren Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Zulrah 75 times.',
    id: 225,
    monster: 'Zulrah',
    name: 'Zulrah Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Zulrah by using the Vengeance spell as the finishing blow.',
    id: 227,
    monster: 'Zulrah',
    name: 'Snake Rebound',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill 3 Snakelings simultaneously.',
    id: 228,
    monster: 'Zulrah',
    name: 'Snake. Snake!? Snaaaaaake!',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Zulrah in less than 1 minute 20 seconds, without a slayer task.',
    id: 230,
    monster: 'Zulrah',
    name: 'Zulrah Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Dagannoth Supreme whilst under attack by Dagannoth Prime and Dagannoth Rex.',
    id: 235,
    monster: 'Dagannoth Supreme',
    name: 'Death to the Archer King',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill all three Dagannoth Kings within 9 seconds of the first one.',
    id: 236,
    monster: 'Dagannoth Supreme',
    name: 'Rapid Succession',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Theatre of Blood 25 times.',
    id: 237,
    monster: 'Theatre of Blood',
    name: 'Theatre of Blood Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Thermonuclear Smoke Devil 20 times.',
    id: 261,
    monster: 'Thermonuclear Smoke Devil',
    name: 'Thermonuclear Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Thermonuclear Smoke Devil without it hitting anyone.',
    id: 262,
    monster: 'Thermonuclear Smoke Devil',
    name: 'Hazard Prevention',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill the Thermonuclear Smoke Devil using only special attacks.',
    id: 263,
    monster: 'Thermonuclear Smoke Devil',
    name: "Spec'd Out",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Venenatis 20 times.',
    id: 265,
    monster: 'Venenatis',
    name: 'Venenatis Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: "Kill Vet'ion 20 times.",
    id: 267,
    monster: "Vet'ion",
    name: "Vet'eran",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Vorkath 50 times.',
    id: 268,
    monster: 'Vorkath',
    name: 'Vorkath Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: "Kill Vorkath's zombified spawn without using crumble undead.",
    id: 271,
    monster: 'Vorkath',
    name: 'Zombie Destroyer',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Vorkath using melee weapons only.',
    id: 273,
    monster: 'Vorkath',
    name: "Stick 'em With the Pointy End",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Complete a Chambers of Xeric Challenge mode raid in the target time.',
    id: 292,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Dust Seeker',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Complete the Chambers of Xeric 25 times.',
    id: 299,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Vanguards without them resetting their health.',
    id: 302,
    monster: 'Chambers of Xeric',
    name: 'Perfectly Balanced',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Vanguards within 10 seconds of the first one dying.',
    id: 303,
    monster: 'Chambers of Xeric',
    name: "Together We'll Fall",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Muttadile without letting her or her baby recover hitpoints from the meat tree.',
    id: 307,
    monster: 'Chambers of Xeric',
    name: 'Mutta-diet',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Abyssal Portal without forcing Vespula to land.',
    id: 308,
    monster: 'Chambers of Xeric',
    name: 'Redemption Enthusiast',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Receive kill-credit for a Stone Guardian without taking damage from falling rocks.',
    id: 311,
    monster: 'Chambers of Xeric',
    name: 'Dancing with Statues',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Complete a Chambers of Xeric raid without anyone dying.',
    id: 312,
    monster: 'Chambers of Xeric',
    name: 'Undying Raid Team',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Receive kill-credit for a Lizardman Shaman without taking damage from any shamans in the room.',
    id: 314,
    monster: 'Chambers of Xeric',
    name: 'Shayzien Specialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Receive kill-credit for the Ice Demon without taking any damage.',
    id: 316,
    monster: 'Chambers of Xeric',
    name: 'Cryo No More',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Receive kill-credit for the Ice Demon without activating the Protect from Range prayer.',
    id: 320,
    monster: 'Chambers of Xeric',
    name: 'Blizzard Dodger',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Finish off the Ice Demon with a fire spell.',
    id: 321,
    monster: 'Chambers of Xeric',
    name: 'Kill It with Fire',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill Zalcano 25 times.',
    id: 328,
    monster: 'Zalcano',
    name: 'Zalcano Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description:
      'Kill Zalcano 5 times in a row without leaving or getting hit by the following: Falling rocks, rock explosions, Zalcano powering up, or standing in a red symbol.',
    id: 329,
    monster: 'Zalcano',
    name: 'Perfect Zalcano',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Receive imbued tephra from a golem.',
    id: 330,
    monster: 'Zalcano',
    name: 'Team Player',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Zalcano as the player who has dealt the most damage to her.',
    id: 331,
    monster: 'Zalcano',
    name: 'The Spurned Hero',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: "Kill K'ril Tsutsaroth 100 times.",
    id: 333,
    monster: "K'ril Tsutsaroth",
    name: "K'ril Tsutsaroth Veteran",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: "Defeat K'ril Tsutsaroth in a private instance using only demonbane spells.",
    id: 336,
    monster: "K'ril Tsutsaroth",
    name: 'The Bane of Demons',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: "Kill K'ril Tsutsaroth in a private instance without taking any of his melee hits.",
    id: 337,
    monster: "K'ril Tsutsaroth",
    name: 'Demonic Defence',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill a Jal-Zek within the Inferno.',
    id: 341,
    monster: 'TzKal-Zuk',
    name: 'Half-Way There',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: "Complete TzHaar-Ket-Rak's second challenge.",
    id: 361,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: 'The II Jad Challenge',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: "Complete TzHaar-Ket-Rak's first challenge in less than 45 seconds.",
    id: 364,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: "TzHaar-Ket-Rak's Speed-Trialist",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: "Complete TzHaar-Ket-Rak's second challenge with only melee.",
    id: 367,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: 'Facing Jad Head-on III',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description:
      'Defeat the Maiden of Sugadinti in the Theatre of Blood: Entry Mode without letting any bloodspawn live for longer than 10 seconds.',
    id: 386,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Anticoagulants',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat the Pestilent Bloat in the Theatre of Blood: Entry Mode with everyone having a salve amulet equipped.',
    id: 387,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Appropriate Tools',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'In the Theatre of Blood: Entry Mode, enter the Pestilent Bloat room from the opposite side.',
    id: 388,
    monster: 'Theatre of Blood: Entry Mode',
    name: "They Won't Expect This",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat the Pestilent Bloat in the Theatre of Blood: Entry Mode by using a halberd special attack as your final attack.',
    id: 389,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Chally Time',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'In the Theatre of Blood: Entry Mode, freeze any 4 Nylocas with a single Ice Barrage spell.',
    id: 390,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Nylocas, On the Rocks',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Sotetseg in the Theatre of Blood: Entry Mode after having split the big ball with your entire team. This must be done with a group size of at least 2.',
    id: 391,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Just To Be Safe',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Xarpus in the Theatre of Blood: Entry Mode without him reflecting any damage to anyone.',
    id: 392,
    monster: 'Theatre of Blood: Entry Mode',
    name: "Don't Look at Me!",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      "Survive Verzik Vitur's pillar phase in the Theatre of Blood: Entry Mode without losing a single pillar.",
    id: 393,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'No-Pillar',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      "Survive Verzik Vitur's second phase in the Theatre of Blood: Entry Mode without anyone getting bounced by Verzik.",
    id: 394,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Attack, Step, Wait',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'In the Theatre of Blood: Entry Mode, successfully pass on the green ball to a team mate.',
    id: 395,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Pass It On',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: "Kill Phosani's Nightmare once.",
    id: 400,
    monster: "Phosani's Nightmare",
    name: "Phosani's Veteran",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Nex once.',
    id: 410,
    monster: 'Nex',
    name: 'Nex Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Nex without anyone dying.',
    id: 412,
    monster: 'Nex',
    name: 'Nex Survivors',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description:
      'Complete the Tombs of Amascut without using any supplies from the Helpful Spirit and without anyone dying. Honey locusts are included in this restriction.',
    id: 425,
    monster: 'Tombs of Amascut',
    name: 'Helpful spirit who?',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Complete the Tombs of Amascut in a group of two or more without anyone dying.',
    id: 430,
    monster: 'Tombs of Amascut',
    name: 'Hardcore Raiders',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Complete the Tombs of Amascut solo without dying.',
    id: 431,
    monster: 'Tombs of Amascut',
    name: 'Hardcore Tombs',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description:
      'Complete the Het room without taking any damage from the light beam and orbs. You must destroy the core after one exposure.',
    id: 432,
    monster: 'Tombs of Amascut',
    name: 'Perfect Het',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description:
      'Complete the Apmeken room in a group of two or more, without anyone allowing any dangers to trigger, standing in venom or being hit by a volatile baboon. You must complete this room in less than three minutes.',
    id: 435,
    monster: 'Tombs of Amascut',
    name: 'Perfect Apmeken',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description:
      'Complete the Crondis room without letting a crocodile get to the tree, without anyone losing water from their container and in under one minute.',
    id: 438,
    monster: 'Tombs of Amascut',
    name: 'Perfect Crondis',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Defeat Akkha without dropping any materialising orbs and without dying yourself.',
    id: 449,
    monster: 'Tombs of Amascut',
    name: 'Dropped the ball',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Ba-Ba after only attacking the non-weakened boulders in the rolling boulder phase, without dying yourself. The Boulderdash invocation must be activated.',
    id: 451,
    monster: 'Tombs of Amascut',
    name: 'No skipping allowed',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Defeat Ba-Ba after destroying four or fewer rolling boulders in total without dying yourself.',
    id: 452,
    monster: 'Tombs of Amascut',
    name: "I'm in a rush",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat the Wardens after staggering the boss a maximum of twice during phase two, without dying yourself.',
    id: 458,
    monster: 'Tombs of Amascut',
    name: 'Down Do Specs',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Tombs of Amascut in Entry mode (or above) 50 times.',
    id: 463,
    monster: 'Tombs of Amascut: Entry Mode',
    name: 'Novice Tomb Raider',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Tombs of Amascut once.',
    id: 468,
    monster: 'Tombs of Amascut',
    name: 'Tomb Explorer',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Tombs of Amascut (Expert mode) once.',
    id: 469,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Expert Tomb Explorer',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Phantom Muspah without running.',
    id: 473,
    monster: 'Phantom Muspah',
    name: "Can't Escape",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Phantom Muspah in less than 3 minutes without a slayer task.',
    id: 475,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill the Phantom Muspah 25 times.',
    id: 479,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: "Drain the Phantom Muspah's Prayer with three different sources in one kill.",
    id: 482,
    monster: 'Phantom Muspah',
    name: 'Versatile Drainer',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Vardorvis in less than 1:15 minutes without a slayer task.',
    id: 485,
    monster: 'Vardorvis',
    name: 'Vardorvis Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Vardorvis once.',
    id: 488,
    monster: 'Vardorvis',
    name: 'Vardorvis Adept',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Whisperer in less than 3:00 without a slayer task.',
    id: 494,
    monster: 'Whisperer',
    name: 'Whisperer Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill the Whisperer once.',
    id: 497,
    monster: 'Whisperer',
    name: 'Whisperer Adept',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Whisperer whilst only being on the Arceuus spellbook.',
    id: 501,
    monster: 'Whisperer',
    name: 'Tentacular',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Leviathan in less than 1:50 without a slayer task.',
    id: 503,
    monster: 'Leviathan',
    name: 'Leviathan Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill the Leviathan once.',
    id: 506,
    monster: 'Leviathan',
    name: 'Leviathan Adept',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Duke Sucellus in less than 1:00 minutes without a slayer task.',
    id: 512,
    monster: 'Duke Sucellus',
    name: 'Duke Sucellus Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Duke Sucellus once.',
    id: 515,
    monster: 'Duke Sucellus',
    name: 'Duke Sucellus Adept',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Defeat a Moon before they start their second special attack.',
    id: 527,
    monster: 'Moons of Peril',
    name: 'High Hitter',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Complete Wave 4 without taking avoidable damage from a Manticore.',
    id: 542,
    monster: 'Fortis Colosseum',
    name: 'Furball',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Complete Wave 7 without the Minotaur ever healing other enemies.',
    id: 545,
    monster: 'Fortis Colosseum',
    name: 'Denied',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill a Jaguar Warrior using a Claw-type weapon special attack.',
    id: 548,
    monster: 'Fortis Colosseum',
    name: 'I was here first!',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill a Tormented Demon.',
    id: 551,
    monster: 'Tormented Demon',
    name: 'Unending Torment',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill a Tormented Demon whilst their shield is inactive.',
    id: 552,
    monster: 'Tormented Demon',
    name: 'Through Fire and Flames',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill two Tormented Demons within 2 seconds.',
    id: 553,
    monster: 'Tormented Demon',
    name: 'Two Times the Torment',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Hit three Tormented Demons within 3 seconds using a ballista or a crossbow.',
    id: 555,
    monster: 'Tormented Demon',
    name: 'Rapid Reload',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Kill Araxxor 25 times.',
    id: 556,
    monster: 'Araxxor',
    name: 'Araxxor Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Kill Araxxor 4 times in 10:00.',
    id: 558,
    monster: 'Araxxor',
    name: 'Araxxor Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Araxxor after destroying six eggs.',
    id: 564,
    monster: 'Araxxor',
    name: 'Relaxxor',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Hueycoatl 25 times.',
    id: 570,
    monster: 'The Hueycoatl',
    name: 'Hueycoatl Veteran',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description:
      "Kill the Hueycoatl perfectly 5 times without leaving. To get a perfect kill, you must not take any avoidable damage from the Hueycoatl's lightning attack, tail slam attack or off-prayer projectile attacks.",
    id: 571,
    monster: 'The Hueycoatl',
    name: 'Perfect Hueycoatl',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Perfection',
  },
  {
    description: 'Kill the Hueycoatl in 2:30',
    id: 576,
    monster: 'The Hueycoatl',
    name: 'Hueycoatl Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Amoxliatl in less than 30 seconds.',
    id: 582,
    monster: 'Amoxliatl',
    name: 'Amoxliatl Speed-Chaser',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Amoxliatl without losing any prayer points.',
    id: 585,
    monster: 'Amoxliatl',
    name: "Without Ralos' Light",
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Kill the Royal Titans without losing any prayer points.',
    id: 596,
    monster: 'Royal Titans',
    name: 'No time to pray',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Restriction',
  },
  {
    description: 'Defeat Yama once.',
    id: 599,
    monster: 'Yama',
    name: 'Yama Adept',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Defeat Yama in an average time of under 3:38 over your last four kills.',
    id: 601,
    monster: 'Yama',
    name: 'Yama Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description:
      'Defeat Yama without the judge being attacked with the wrong style and without taking more than one instance of damage each time you are exiled from the arena.',
    id: 607,
    monster: 'Yama',
    name: 'Back so soon?',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl at delve level 3.',
    id: 610,
    monster: 'Doom of Mokhaiotl',
    name: 'Doom Adept',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Kill Count',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl during its Melee charge phase.',
    id: 613,
    monster: 'Doom of Mokhaiotl',
    name: 'Exposed Doom',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Mechanical',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl level 1 in less than 30 seconds.',
    id: 621,
    monster: 'Doom of Mokhaiotl',
    name: 'Doom Crawler',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
  {
    description: 'Kill Brutus in less than 2 seconds.',
    id: 634,
    monster: 'Brutus',
    name: 'Brutus Speed-Trialist',
    points: 4,
    tier: CombatAchievementTier.Elite,
    type: 'Speed',
  },
];
