import { CombatAchievementTask, CombatAchievementTier } from '../CombatAchievement';

/**
 * Grandmaster-tier Combat Achievement tasks, authored directly in TypeScript.
 *
 * Source: https://oldschool.runescape.wiki/w/Combat_Achievements/Grandmaster
 */
export const GRANDMASTER_COMBAT_ACHIEVEMENTS: CombatAchievementTask[] = [
  {
    description: "Kill Kree'arra by only dealing damage to him with a salamander.",
    id: 14,
    monster: "Kree'arra",
    name: 'The Worst Ranged Weapon',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: "Kill Kree'arra 30 times in a private instance without leaving the room.",
    id: 15,
    monster: "Kree'arra",
    name: 'Feather Hunter',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Stamina',
  },
  {
    description:
      'Kill General Graardor 2 times consecutively in a private instance without taking any damage from his bodyguards.',
    id: 21,
    monster: 'General Graardor',
    name: 'Defence Matters',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Kill General Graardor in a private instance without taking any damage from the boss or bodyguards.',
    id: 22,
    monster: 'General Graardor',
    name: 'Keep Away',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Kill General Graardor 15 times in a private instance without leaving the room.',
    id: 23,
    monster: 'General Graardor',
    name: 'Ourg Killer',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Stamina',
  },
  {
    description: 'Kill the Grotesque Guardians in less than 1:20 minutes.',
    id: 94,
    monster: 'Grotesque Guardians',
    name: 'Grotesque Guardians Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Corrupted Gauntlet 50 times.',
    id: 100,
    monster: 'Corrupted Hunllef',
    name: 'Corrupted Gauntlet Grandmaster',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Corrupted Hunllef without making an egniol potion within the Corrupted Gauntlet.',
    id: 104,
    monster: 'Corrupted Hunllef',
    name: 'Egniol Diet II',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill the Corrupted Hunllef without making more than one attuned weapon.',
    id: 106,
    monster: 'Corrupted Hunllef',
    name: 'Wolf Puncher II',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Complete a Corrupted Gauntlet in less than 6 minutes and 30 seconds.',
    id: 108,
    monster: 'Corrupted Hunllef',
    name: 'Corrupted Gauntlet Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Gauntlet in less than 4 minutes.',
    id: 118,
    monster: 'Crystalline Hunllef',
    name: 'Gauntlet Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description:
      "Kill the Alchemical Hydra using only Dharok's Greataxe as a weapon whilst having no more than 10 Hitpoints throughout the entire fight.",
    id: 143,
    monster: 'Alchemical Hydra',
    name: 'No Pressure',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill the Alchemical Hydra in less than 1 minute 20 seconds.',
    id: 145,
    monster: 'Alchemical Hydra',
    name: 'Alchemical Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Fight Caves without TzTok-Jad being healed by a Yt-HurKot.',
    id: 151,
    monster: 'TzTok-Jad',
    name: 'Denying the Healers II',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Fight Caves without losing any prayer points.',
    id: 154,
    monster: 'TzTok-Jad',
    name: 'No Time for a Drink',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Complete the Fight Caves in less than 26 minutes and 30 seconds.',
    id: 156,
    monster: 'TzTok-Jad',
    name: 'Fight Caves Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill the Nightmare solo without the Parasites healing the boss for more than 100 health.',
    id: 186,
    monster: 'The Nightmare',
    name: 'Terrible Parent',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Nightmare without any player losing any prayer points.',
    id: 190,
    monster: 'The Nightmare',
    name: 'A Long Trip',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Defeat the Nightmare (Solo) in less than 16 minutes.',
    id: 193,
    monster: 'The Nightmare',
    name: 'Nightmare (Solo) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Defeat the Nightmare (5-scale) in less than 3:30 minutes.',
    id: 196,
    monster: 'The Nightmare',
    name: 'Nightmare (5-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill Commander Zilyana in a private instance without taking any damage from the boss or bodyguards.',
    id: 214,
    monster: 'Commander Zilyana',
    name: 'Animal Whisperer',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Kill Commander Zilyana 50 times in a privately rented instance without leaving the room.',
    id: 217,
    monster: 'Commander Zilyana',
    name: 'Peach Conjurer',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Stamina',
  },
  {
    description: 'Kill Zulrah in less than 54 seconds, without a slayer task.',
    id: 232,
    monster: 'Zulrah',
    name: 'Zulrah Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood 150 times.',
    id: 239,
    monster: 'Theatre of Blood',
    name: 'Theatre of Blood Grandmaster',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description:
      'Complete the Theatre of Blood without anyone dying through any means and whilst everyone in the team completes the following Combat Achievement tasks in a single run: "Perfect Maiden", "Perfect Bloat", "Perfect Nylocas", "Perfect Sotetseg", "Perfect Xarpus" and "Perfect Verzik".',
    id: 243,
    monster: 'Theatre of Blood',
    name: 'Perfect Theatre',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description:
      'Complete the Theatre of Blood without any member of the team equipping a non-barrows weapon (except Dawnbringer).',
    id: 252,
    monster: 'Theatre of Blood',
    name: 'Morytania Only',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Complete the Theatre of Blood (Duo) in less than 26 minutes.',
    id: 254,
    monster: 'Theatre of Blood',
    name: 'Theatre (Duo) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood (Trio) in less than 17 minutes and 30 seconds.',
    id: 256,
    monster: 'Theatre of Blood',
    name: 'Theatre (Trio) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood (4-scale) in less than 15 minutes.',
    id: 258,
    monster: 'Theatre of Blood',
    name: 'Theatre (4-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood (5-scale) in less than 14 minutes and 15 seconds.',
    id: 260,
    monster: 'Theatre of Blood',
    name: 'Theatre (5-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill Vorkath without losing any prayer points.',
    id: 274,
    monster: 'Vorkath',
    name: 'Faithless Encounter',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Vorkath with only your fists.',
    id: 275,
    monster: 'Vorkath',
    name: 'The Fremennik Way',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Vorkath in less than 54 seconds.',
    id: 277,
    monster: 'Vorkath',
    name: 'Vorkath Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Chambers of Xeric: Challenge Mode 25 times.',
    id: 289,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM Grandmaster',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge Mode (Solo) in less than 38 minutes and 30 seconds.',
    id: 294,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM (Solo) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge Mode (5-scale) in less than 25 minutes.',
    id: 296,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM (5-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge Mode (Trio) in less than 27 minutes.',
    id: 298,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM (Trio) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Chambers of Xeric 150 times.',
    id: 301,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric Grandmaster',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Complete a Chambers of Xeric (Solo) in less than 17 minutes.',
    id: 323,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric (Solo) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric (5-scale) in less than 12 minutes and 30 seconds.',
    id: 325,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric (5-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric (Trio) in less than 14 minutes and 30 seconds.',
    id: 327,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric (Trio) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: "Kill K'ril Tsutsaroth in a private instance without ever being hit by his bodyguards.",
    id: 338,
    monster: "K'ril Tsutsaroth",
    name: 'Demon Whisperer',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: "Kill K'ril Tsutsaroth 20 times in a private instance without leaving the room.",
    id: 340,
    monster: "K'ril Tsutsaroth",
    name: 'Ash Collector',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Stamina',
  },
  {
    description: 'Complete the Inferno 5 times.',
    id: 342,
    monster: 'TzKal-Zuk',
    name: 'Inferno Grandmaster',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Kill Tzkal-Zuk without letting Jal-ImKot dig during any wave in the Inferno.',
    id: 343,
    monster: 'TzKal-Zuk',
    name: 'The Floor Is Lava',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Complete wave 68 of the Inferno within 30 seconds of the first JalTok-Jad dying.',
    id: 344,
    monster: 'TzKal-Zuk',
    name: 'Playing with Jads',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Kill Tzkal-Zuk without being attacked by TzKal-Zuk and without taking damage from a JalTok-Jad.',
    id: 345,
    monster: 'TzKal-Zuk',
    name: 'No Luck Required',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Kill Tzkal-Zuk without letting your hitpoints fall below 50 during any wave in the Inferno.',
    id: 347,
    monster: 'TzKal-Zuk',
    name: "Wasn't Even Close",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Tzkal-Zuk without equipping a Twisted Bow within the Inferno.',
    id: 348,
    monster: 'TzKal-Zuk',
    name: 'Budget Setup',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Tzkal-Zuk without using any magic spells during any wave in the Inferno.',
    id: 349,
    monster: 'TzKal-Zuk',
    name: 'Nibbler Chaser',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Tzkal-Zuk without equipping any range or mage weapons before wave 69.',
    id: 350,
    monster: 'TzKal-Zuk',
    name: 'Facing Jad Head-on II',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Tzkal-Zuk without killing the JalTok-Jad which spawns during wave 69.',
    id: 351,
    monster: 'TzKal-Zuk',
    name: 'Jad? What Are You Doing Here?',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Complete the Inferno in less than 65 minutes.',
    id: 352,
    monster: 'TzKal-Zuk',
    name: 'Inferno Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: "Complete TzHaar-Ket-Rak's sixth challenge.",
    id: 363,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: 'The VI Jad Challenge',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: "Complete TzHaar-Ket-Rak's fifth challenge in less than 5 minutes.",
    id: 366,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: "TzHaar-Ket-Rak's Speed-Runner",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: "Complete TzHaar-Ket-Rak's fifth and sixth challenges back to back without failing.",
    id: 370,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: "It Wasn't a Fluke",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description:
      'Defeat the Maiden of Sugadinti in the Theatre of Blood: Hard Mode without letting blood spawns create more than 15 blood trails.',
    id: 372,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Stop Right There!',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat the Pestilent Bloat in the Theatre of Blood: Hard Mode with at least 3 people in the room, without anyone in your team standing on top of each other.',
    id: 373,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Personal Space',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'In the Theatre of Blood: Hard Mode, complete the Nylocas room without ever letting the Nylocas Prinkipas change styles.',
    id: 374,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Royal Affairs',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Sotetseg in the Theatre of Blood: Hard Mode without anyone sharing the ball with anyone, without anyone dying, and without anyone taking damage from any of its other attacks or stepping on the wrong tile in the maze.',
    id: 375,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Harder Mode I',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description:
      'Defeat Xarpus in the Theatre of Blood: Hard Mode after letting the exhumeds heal him to full health and without anyone in the team taking any damage.',
    id: 376,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Harder Mode II',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description:
      "Defeat Verzik Vitur's in the Theatre of Blood: Hard Mode without anyone in your team causing a Nylocas to explode by getting too close.",
    id: 377,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Nylo Sniper',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'When Verzik Vitur in the Theatre of Blood: Hard Mode uses her yellow power blast attack while the tornadoes are active, have everyone get through the attack without taking damage. This cannot be completed with one player alive',
    id: 378,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Team Work Makes the Dream Work',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Verzik Vitur in the Theatre of Blood: Hard Mode without anyone attacking her with a melee weapon during her third phase.',
    id: 379,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Harder Mode III',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description:
      'Complete the Theatre of Blood: Hard Mode within the challenge time, with no deaths and without anyone buying anything from a supply chest.',
    id: 380,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Pack Like a Yak',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Complete the Theatre of Blood: Hard Mode (Trio) with an overall time of less than 23 minutes.',
    id: 382,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Theatre: HM (Trio) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood: Hard Mode (4-scale) with an overall time of less than 21 minutes.',
    id: 383,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Theatre: HM (4-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood: Hard Mode (5-scale) with an overall time of less than 19 minutes.',
    id: 384,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Theatre: HM (5-Scale) Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood: Hard Mode 50 times.',
    id: 385,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Theatre of Blood: HM Grandmaster',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: "Kill Phosani's Nightmare 25 times.",
    id: 402,
    monster: "Phosani's Nightmare",
    name: "Phosani's Grandmaster",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description:
      "Kill Phosani's Nightmare while only taking damage from husks, power blasts and weakened Parasites. Also, without having your attacks slowed by the Nightmare Spores or letting a Sleepwalker reach Phosani's Nightmare.",
    id: 403,
    monster: "Phosani's Nightmare",
    name: "Perfect Phosani's Nightmare",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: "Kill Phosani's Nightmare within 6 minutes.",
    id: 405,
    monster: "Phosani's Nightmare",
    name: "Phosani's Speedrunner",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: "Kill Phosani's Nightmare 5 times in a row without leaving Phosani's Dream.",
    id: 409,
    monster: "Phosani's Nightmare",
    name: "Can't Wake Up",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Stamina',
  },
  {
    description: 'Kill Nex with two or less players at the start of the fight.',
    id: 417,
    monster: 'Nex',
    name: 'Nex Duo',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Nex whilst a player is coughing.',
    id: 418,
    monster: 'Nex',
    name: 'I should see a doctor',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description:
      'Kill Nex whilst completing the requirements for "There is no escape", "Shadows move", "A siphon will solve this", and "Contain this!"',
    id: 419,
    monster: 'Nex',
    name: 'Perfect Nex',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Complete the Tombs of Amascut (expert) within 20 mins at any group size.',
    id: 422,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Tombs Speed Runner II',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Complete the Tombs of Amascut (expert) within 18 mins in a group of 8.',
    id: 423,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Tombs Speed Runner III',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: "Complete 'Perfect Het' and 'Perfect Akkha' in a single run of the Tombs of Amascut.",
    id: 434,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Perfection of Het',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: "Complete 'Perfect Apmeken' and 'Perfect Ba-Ba' in a single run of the Tombs of Amascut.",
    id: 437,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Perfection of Apmeken',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: "Complete 'Perfect Crondis' and 'Perfect Zebak' in a single run of the Tombs of Amascut.",
    id: 440,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Perfection of Crondis',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: "Complete 'Perfect Scabaras' and 'Perfect Kephri' in a single run of Tombs of Amascut.",
    id: 443,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Perfection of Scabaras',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: "Complete 'Perfect Wardens' at expert or above.",
    id: 445,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Insanity',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Complete the Tombs of Amascut at raid level 500 or above without anyone dying.',
    id: 446,
    monster: 'Tombs of Amascut: Expert Mode',
    name: "Amascut's Remnant",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'Complete a Tombs of Amascut raid with every single boss invocation activated and without anyone dying.',
    id: 448,
    monster: 'Tombs of Amascut: Expert Mode',
    name: "Maybe I'm the boss.",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Akkha with all Akkha invocations activated and the path levelled up to at least four, without dying yourself.',
    id: 450,
    monster: 'Tombs of Amascut: Expert Mode',
    name: "Akkhan't Do it",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description:
      "Defeat Zebak without losing a single prayer point. You must also meet the conditions of the 'Rockin' Around The Croc' achievement.",
    id: 454,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'All Praise Zebak',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Tombs of Amascut (Expert mode) 50 times.',
    id: 471,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Expert Tomb Raider',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Phantom Muspah in less than 1 minute and 30 seconds without a slayer task.',
    id: 477,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: "Kill the Phantom Muspah whilst completing Walk Straight Pray True, Space is Tight & Can't Escape.",
    id: 484,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Manipulator',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Kill Vardorvis in less than 0:55 without a slayer task.',
    id: 487,
    monster: 'Vardorvis',
    name: 'Vardorvis Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill Awakened Vardorvis.',
    id: 490,
    monster: 'Vardorvis',
    name: 'Vardorvis Sleeper',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description:
      "Kill Vardorvis after surviving for 3 minutes of Vardorvis' max speed, and never leaving the centre 25 tiles.",
    id: 492,
    monster: 'Vardorvis',
    name: 'Axe Enthusiast',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Whisperer in less than 2:05 without a slayer task.',
    id: 496,
    monster: 'Whisperer',
    name: 'Whisperer Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill the Awakened Whisperer.',
    id: 499,
    monster: 'Whisperer',
    name: 'Whispered',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Whisperer whilst spending less than 6 seconds in the pre-enrage shadow realm.',
    id: 502,
    monster: 'Whisperer',
    name: 'Dark Memories',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill the Leviathan in less than 1:10 without a slayer task.',
    id: 505,
    monster: 'Leviathan',
    name: 'Leviathan Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill the Awakened Leviathan.',
    id: 508,
    monster: 'Leviathan',
    name: 'Leviathan Sleeper',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description:
      'Kill the Leviathan using only Mithril ammunition whilst having no more than 25 Hitpoints throughout the entire fight.',
    id: 511,
    monster: 'Leviathan',
    name: 'Unconventional',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill Duke Sucellus in less than 40 seconds without a slayer task.',
    id: 514,
    monster: 'Duke Sucellus',
    name: 'Duke Sucellus Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill Awakened Duke Sucellus.',
    id: 517,
    monster: 'Duke Sucellus',
    name: 'Duke Sucellus Sleeper',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Kill Duke Sucellus whilst only attacking the boss on the same tick Duke attacks you.',
    id: 520,
    monster: 'Duke Sucellus',
    name: 'Mirror Image',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Defeat Sol Heredit 10 times.',
    id: 539,
    monster: 'Fortis Colosseum',
    name: 'Colosseum Grand Champion',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Defeat Sol Heredit without running during the fight with him.',
    id: 541,
    monster: 'Fortis Colosseum',
    name: 'Slow Dancing in the Sand',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Defeat Sol Heredit without taking any damage from his Spear, Shield, Grapple or Triple Attack.',
    id: 543,
    monster: 'Fortis Colosseum',
    name: 'Perfect Footwork',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Defeat Sol Heredit with "Bees II", "Quartet" and "Solarflare II" modifiers active.',
    id: 547,
    monster: 'Fortis Colosseum',
    name: 'Reinforcements',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Colosseum with a total time of 24:00 or less.',
    id: 550,
    monster: 'Fortis Colosseum',
    name: 'Colosseum Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill Araxxor 6 times in 10:00.',
    id: 560,
    monster: 'Araxxor',
    name: 'Araxxor Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Kill Araxxor perfectly, without hitting it during the enrage phase.',
    id: 562,
    monster: 'Araxxor',
    name: 'Perfect Araxxor 2',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Kill Araxxor without the boss ever moving.',
    id: 565,
    monster: 'Araxxor',
    name: 'Swimming in Venom',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Kill the Hueycoatl in 2:30 with three or fewer players.',
    id: 578,
    monster: 'The Hueycoatl',
    name: 'Hueycoatl Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Defeat Yama in an average time of under 2:34 over your last four kills.',
    id: 603,
    monster: 'Yama',
    name: 'Yama Speed-Runner',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description:
      "Defeat Yama whilst completing 'Shadow Dancer', 'Fire Fighter', 'Back so soon?' and without taking any other avoidable damage.",
    id: 608,
    monster: 'Yama',
    name: 'Contract Choreographer',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Defeat Yama under the elevated conditions of one of his non-standard contracts.',
    id: 609,
    monster: 'Yama',
    name: 'Contractually Unbound',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Kill Count',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl at delve level 16.',
    id: 612,
    monster: 'Doom of Mokhaiotl',
    name: "It's Dark Down Here",
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Stamina',
  },
  {
    description:
      'Defeat the Doom of Mokhaiotl levels 1-8 without taking any damage from the boss, letting any grubs be absorbed, or stepping in acid blood.',
    id: 616,
    monster: 'Doom of Mokhaiotl',
    name: 'Perfect Doom',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Perfection',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 without restoring your prayer points through any method.',
    id: 617,
    monster: 'Doom of Mokhaiotl',
    name: 'The Praying Mantis',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 whilst only damaging the boss with one-handed melee attacks.',
    id: 618,
    monster: 'Doom of Mokhaiotl',
    name: 'Duel of Mokhaiotl',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 without equipping a demonbane weapon.',
    id: 619,
    monster: 'Doom of Mokhaiotl',
    name: 'Darkness Is Your Ally?',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Restriction',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 in less than 7:15.',
    id: 623,
    monster: 'Doom of Mokhaiotl',
    name: 'Doom Racer',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Speed',
  },
  {
    description: 'Clear at least 8 acid splats in a single Volatile Earth special attack.',
    id: 624,
    monster: 'Doom of Mokhaiotl',
    name: 'Mopping up',
    points: 6,
    tier: CombatAchievementTier.Grandmaster,
    type: 'Mechanical',
  },
];
