import { CombatAchievementTask, CombatAchievementTier } from '../CombatAchievement';

/**
 * Hard-tier Combat Achievement tasks, authored directly in TypeScript.
 *
 * Source: https://oldschool.runescape.wiki/w/Combat_Achievements/Hard
 */
export const HARD_COMBAT_ACHIEVEMENTS: CombatAchievementTask[] = [
  {
    description: 'Kill the Abyssal Sire 20 times.',
    id: 1,
    monster: 'Abyssal Sire',
    name: 'Abyssal Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Abyssal Sire without letting any Scion mature.',
    id: 3,
    monster: 'Abyssal Sire',
    name: 'They Grow Up Too Fast',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Abyssal Sire without being hit by any external tentacles.',
    id: 5,
    monster: 'Abyssal Sire',
    name: "Don't Whip Me",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Abyssal Sire without taking damage from any miasma pools.',
    id: 7,
    monster: 'Abyssal Sire',
    name: "Don't Stop Moving",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: "Kill Kree'arra 50 times.",
    id: 9,
    monster: "Kree'arra",
    name: "Kree'arra Adept",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: "Finish off Kree'arra whilst all of his bodyguards are dead.",
    id: 12,
    monster: "Kree'arra",
    name: 'Airborne Showdown',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill General Graardor 50 times.',
    id: 16,
    monster: 'General Graardor',
    name: 'General Graardor Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill General Graardor whilst he is immobilized&#91;sic&#93;.',
    id: 18,
    monster: 'General Graardor',
    name: 'Ourg Freezer',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Finish off General Graardor whilst all of his bodyguards are dead.',
    id: 20,
    monster: 'General Graardor',
    name: 'General Showdown',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill Karil using only damage dealt by special attacks.',
    id: 29,
    monster: 'Barrows',
    name: 'Just Like That',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description:
      'Kill all six Barrows Brothers and loot the Barrows chest without ever having more than 0 prayer points.',
    id: 30,
    monster: 'Barrows',
    name: 'Faithless Crypt Run',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill Callisto 10 times.',
    id: 42,
    monster: 'Callisto',
    name: 'Callisto Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Skotizo 5 times.',
    id: 45,
    monster: 'Skotizo',
    name: 'Skotizo Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Chaos Elemental 10 times.',
    id: 57,
    monster: 'Chaos Elemental',
    name: 'Chaos Elemental Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Chaos Elemental without it unequipping any of your items.',
    id: 59,
    monster: 'Chaos Elemental',
    name: 'Hoarder',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Chaos Elemental without taking any damage from its attacks.',
    id: 60,
    monster: 'Chaos Elemental',
    name: 'The Flincher',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: 'Kill the Chaos Fanatic 25 times.',
    id: 62,
    monster: 'Chaos Fanatic',
    name: 'Chaos Fanatic Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description:
      'Kill the Chaos Fanatic 10 times without drinking any potion which restores prayer or leaving the Wilderness.',
    id: 64,
    monster: 'Chaos Fanatic',
    name: 'Praying to the Gods',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill the Crazy Archaeologist 25 times.',
    id: 71,
    monster: 'Crazy Archaeologist',
    name: 'Crazy Archaeologist Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Grotesque Guardians 25 times.',
    id: 82,
    monster: 'Grotesque Guardians',
    name: 'Grotesque Guardians Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: "Kill the Grotesque Guardians without taking damage from Dusk's blinding attack.",
    id: 84,
    monster: 'Grotesque Guardians',
    name: "Don't Look at the Eclipse",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: "Kill the Grotesque Guardians without taking damage from Dusk's prison attack.",
    id: 85,
    monster: 'Grotesque Guardians',
    name: 'Prison Break',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: "Kill the Grotesque Guardians without taking damage from Dawn's rockfall attack.",
    id: 86,
    monster: 'Grotesque Guardians',
    name: 'Granite Footwork',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Grotesque Guardians without letting Dawn receive any healing from her orbs.',
    id: 87,
    monster: 'Grotesque Guardians',
    name: 'Heal No More',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Grotesque Guardians without being hit by any lightning attacks.',
    id: 88,
    monster: 'Grotesque Guardians',
    name: 'Static Awareness',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill Hespori 5 times.',
    id: 123,
    monster: 'Hespori',
    name: 'Hespori Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Finish off Hespori with a special attack.',
    id: 124,
    monster: 'Hespori',
    name: "Hesporisn't",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill all of Hesporis flowers within 5 seconds.',
    id: 125,
    monster: 'Hespori',
    name: 'Weed Whacker',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Kalphite Queen 25 times.',
    id: 157,
    monster: 'Kalphite Queen',
    name: 'Kalphite Queen Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Kalphite Queen while her defence was last lowered by you.',
    id: 159,
    monster: 'Kalphite Queen',
    name: 'Chitin Penetrator',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill The King Black Dragon 10 times in a private instance without leaving the instance.',
    id: 167,
    monster: 'King Black Dragon',
    name: 'Who Is the King Now?',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description: 'Kill the Kraken 20 times.',
    id: 168,
    monster: 'Kraken',
    name: 'Kraken Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Kraken after killing all four tentacles.',
    id: 169,
    monster: 'Kraken',
    name: 'Unnecessary Optimisation',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Kraken 25 times in a private instance without leaving the room.',
    id: 170,
    monster: 'Kraken',
    name: "Krakan't Hurt Me",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description: 'Kill the Giant Mole without her burrowing more than 2 times.',
    id: 179,
    monster: 'Giant Mole',
    name: 'Why Are You Running?',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Giant Mole within 10 seconds of her resurfacing.',
    id: 181,
    monster: 'Giant Mole',
    name: 'Whack-a-Mole',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill The Nightmare once.',
    id: 183,
    monster: 'The Nightmare',
    name: 'Nightmare Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dagannoth Prime 25 times.',
    id: 198,
    monster: 'Dagannoth Prime',
    name: 'Dagannoth Prime Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dagannoth Rex 25 times.',
    id: 202,
    monster: 'Dagannoth Rex',
    name: 'Dagannoth Rex Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Sarachnis without her using her range attack twice in a row.',
    id: 208,
    monster: 'Sarachnis',
    name: 'Ready to Pounce',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill Sarachnis without her dealing damage to anyone.',
    id: 209,
    monster: 'Sarachnis',
    name: 'Inspect Repellent',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: 'Kill Commander Zilyana 50 times.',
    id: 211,
    monster: 'Commander Zilyana',
    name: 'Commander Zilyana Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Finish off Commander Zilyana while all of her bodyguards are dead.',
    id: 213,
    monster: 'Commander Zilyana',
    name: 'Commander Showdown',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill Scorpia 10 times.',
    id: 218,
    monster: 'Scorpia',
    name: 'Scorpia Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Scorpia without taking any damage from her.',
    id: 220,
    monster: 'Scorpia',
    name: "I Can't Reach That",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: 'Kill Scorpia without killing her guardians.',
    id: 221,
    monster: 'Scorpia',
    name: 'Guardians No More',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill Zulrah 25 times.',
    id: 224,
    monster: 'Zulrah',
    name: 'Zulrah Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dagannoth Supreme 25 times.',
    id: 234,
    monster: 'Dagannoth Supreme',
    name: 'Dagannoth Supreme Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Venenatis 10 times.',
    id: 264,
    monster: 'Venenatis',
    name: 'Venenatis Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: "Kill Vet'ion 10 times.",
    id: 266,
    monster: "Vet'ion",
    name: "Vet'ion Adept",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Subdue the Wintertodt after earning 3000 or more points.',
    id: 286,
    monster: 'Wintertodt',
    name: 'Why Fletch?',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description: "Kill K'ril Tsutsaroth 50 times.",
    id: 332,
    monster: "K'ril Tsutsaroth",
    name: "K'ril Tsutsaroth Adept",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: "Receive kill-credit for K'ril Tsutsaroth without him using his special attack.",
    id: 334,
    monster: "K'ril Tsutsaroth",
    name: 'Yarr No More',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: "Finish off K'ril Tsutsaroth whilst all of his bodyguards are dead.",
    id: 335,
    monster: "K'ril Tsutsaroth",
    name: 'Demonic Showdown',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: "Finish off K'ril Tsutsaroth with a demonbane weapon.",
    id: 339,
    monster: "K'ril Tsutsaroth",
    name: 'Demonbane Weaponry II',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Subdue Tempoross while wearing any variation of the angler outfit.',
    id: 355,
    monster: 'Tempoross',
    name: 'Dress Like You Mean It',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Subdue Tempoross, getting rewarded with 10 reward permits from a single Tempoross fight.',
    id: 358,
    monster: 'Tempoross',
    name: 'Why Cook?',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Theatre of Blood: Entry Mode 1 time.',
    id: 397,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Theatre of Blood: SM Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Tombs of Amascut in Entry mode (or above) once.',
    id: 461,
    monster: 'Tombs of Amascut: Entry Mode',
    name: 'Novice Tomb Explorer',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Tombs of Amascut in Entry mode (or above) 25 times.',
    id: 462,
    monster: 'Tombs of Amascut: Entry Mode',
    name: 'Novice Tomb Looter',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Complete a Tombs of Amascut raid at level 50 or above.',
    id: 464,
    monster: 'Tombs of Amascut: Entry Mode',
    name: "Movin' on up",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Complete a Tombs of Amascut raid at level 100 or above.',
    id: 465,
    monster: 'Tombs of Amascut: Entry Mode',
    name: 'Confident Raider',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill the Phantom Muspah.',
    id: 478,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Defeat the Eclipse moon by only attacking its clones.',
    id: 526,
    monster: 'Moons of Peril',
    name: 'The Clone Zone',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Open the Reward Chest 25 times.',
    id: 530,
    monster: 'Moons of Peril',
    name: 'Perilous Champion',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Defeat all the Moons in one run while only taking damage from regular attacks.',
    id: 531,
    monster: 'Moons of Peril',
    name: 'Perilous Dancer',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: 'Defeat a Moon without consuming any supplies.',
    id: 532,
    monster: 'Moons of Peril',
    name: 'Fortified',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Defeat a Moon using its associated weapon drop.',
    id: 533,
    monster: 'Moons of Peril',
    name: 'Betrayal',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Defeat all three Moons in one run in under 6 minutes.',
    id: 536,
    monster: 'Moons of Peril',
    name: 'Moons of Peril Speed-Chaser',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Speed',
  },
  {
    description: 'Defeat 30 Moons of Peril bosses without leaving the dungeon.',
    id: 537,
    monster: 'Moons of Peril',
    name: 'Fat of the Land',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description: 'Kill the Hueycoatl 10 times.',
    id: 569,
    monster: 'The Hueycoatl',
    name: 'Hueycoatl Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Hueycoatl whilst it is vulnerable.',
    id: 572,
    monster: 'The Hueycoatl',
    name: 'Pillar Lover',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Hueycoatl whilst wearing two pieces of Hueycoatl armour.',
    id: 575,
    monster: 'The Hueycoatl',
    name: "I'm your son",
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill Amoxliatl 20 times.',
    id: 580,
    monster: 'Amoxliatl',
    name: 'Amoxliatl Adept',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Kill Count',
  },
  {
    description: 'Kill Amoxliatl in less than 1 minute.',
    id: 581,
    monster: 'Amoxliatl',
    name: 'Amoxliatl Speed-Trialist',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Speed',
  },
  {
    description: 'Kill Amoxliatl without taking any damage.',
    id: 583,
    monster: 'Amoxliatl',
    name: 'Nagua Negation',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: 'Kill Amoxliatl 10 times without leaving her chamber.',
    id: 586,
    monster: 'Amoxliatl',
    name: 'Kemo Makti',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description: 'Kill Amoxliatl without any of her unstable ice shattering.',
    id: 587,
    monster: 'Amoxliatl',
    name: 'Totally Shattered',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
  {
    description:
      'Kill the Royal Titans without getting hit by any avoidable damage. This includes: Melee attacks, Explosions from the ice or fire elemental, Icicle or fire spawn damage, and Ice or fire pulse attacks.',
    id: 588,
    monster: 'Royal Titans',
    name: 'Perfect Royal Titans',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Perfection',
  },
  {
    description: 'Kill the Royal Titans in less than 1:30 minutes.',
    id: 592,
    monster: 'Royal Titans',
    name: 'Royal Titan Speed-Runner',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Speed',
  },
  {
    description:
      'Kill the Royal Titans 15 times without anyone leaving the instance. If a player joins the fight, the current streak will be reset to 0. If a player leaves the fight, the task will be failed and a new instance will need to be created.',
    id: 593,
    monster: 'Royal Titans',
    name: 'Titan Killer',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description:
      'Kill the Royal Titans while extinguishing all fires and melting all icicles before they dissipate naturally.',
    id: 595,
    monster: 'Royal Titans',
    name: 'I need room',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill the Shellbane Gryphon 25 times without leaving the cave.',
    id: 629,
    monster: 'Shellbane gryphon',
    name: 'Shellbane Survivor',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Stamina',
  },
  {
    description:
      'Kill the Shellbane Gryphon 5 times without leaving the cave, while wearing gear weighing less than 40kg.',
    id: 631,
    monster: 'Shellbane gryphon',
    name: 'Featherweight Fighter',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Restriction',
  },
  {
    description: 'Kill Brutus without being attacked.',
    id: 636,
    monster: 'Brutus',
    name: 'Smarter than a Cow',
    points: 3,
    tier: CombatAchievementTier.Hard,
    type: 'Mechanical',
  },
];
