import { CombatAchievementTask, CombatAchievementTier } from '../CombatAchievement';

/**
 * Master-tier Combat Achievement tasks, authored directly in TypeScript.
 *
 * Source: https://oldschool.runescape.wiki/w/Combat_Achievements/Master
 */
export const MASTER_COMBAT_ACHIEVEMENTS: CombatAchievementTask[] = [
  {
    description: "Kill Kree'arra in a private instance without ever attacking him directly.",
    id: 11,
    monster: "Kree'arra",
    name: 'Collateral Damage',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      "Kill Kree'arra in a private instance without taking any melee damage from the boss or his bodyguards.",
    id: 13,
    monster: "Kree'arra",
    name: 'Swoop No More',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Skotizo with the final source of damage being a Chinchompa explosion.',
    id: 50,
    monster: 'Skotizo',
    name: 'Precise Positioning',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill Cerberus 150 times.',
    id: 52,
    monster: 'Cerberus',
    name: 'Cerberus Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill Cerberus without any of the Summoned Souls being spawned.',
    id: 53,
    monster: 'Cerberus',
    name: 'Arooo No More',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Corporeal Beast 50 times.',
    id: 66,
    monster: 'Corporeal Beast',
    name: 'Corporeal Beast Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description:
      'Kill the Grotesque Guardians 5 times in a row without leaving the instance, whilst completing the Perfect Grotesque Guardians task every time.',
    id: 91,
    monster: 'Grotesque Guardians',
    name: 'Perfect Grotesque Guardians II',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill the Grotesque Guardians in less than 1:40 minutes.',
    id: 93,
    monster: 'Grotesque Guardians',
    name: 'Grotesque Guardians Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Grotesque Guardians 20 times without leaving the instance.',
    id: 96,
    monster: 'Grotesque Guardians',
    name: "... 'til Dawn",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Stamina',
  },
  {
    description: 'Complete the Corrupted Gauntlet 10 times.',
    id: 99,
    monster: 'Corrupted Hunllef',
    name: 'Corrupted Gauntlet Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description:
      'Kill the Corrupted Hunllef without taking damage from: Tornadoes, Damaging Floor or Stomp Attacks. Also, do not take damage off prayer and do not attack the Corrupted Hunllef with the wrong weapon.',
    id: 102,
    monster: 'Corrupted Hunllef',
    name: 'Perfect Corrupted Hunllef',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill the Corrupted Hunllef without making any armour within the Corrupted Gauntlet.',
    id: 103,
    monster: 'Corrupted Hunllef',
    name: "Defence Doesn't Matter II",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill the Corrupted Hunllef with a full set of perfected corrupted armour equipped.',
    id: 105,
    monster: 'Corrupted Hunllef',
    name: 'Corrupted Warrior',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Complete a Corrupted Gauntlet in less than 7 minutes and 30 seconds.',
    id: 107,
    monster: 'Corrupted Hunllef',
    name: 'Corrupted Gauntlet Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete the Gauntlet 20 times.',
    id: 110,
    monster: 'Crystalline Hunllef',
    name: 'Gauntlet Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description:
      'Kill the Crystalline Hunllef without taking damage from: Tornadoes, Damaging Floor or Stomp Attacks. Also, do not take damage off prayer and do not attack the Crystalline Hunllef with the wrong weapon.',
    id: 112,
    monster: 'Crystalline Hunllef',
    name: 'Perfect Crystalline Hunllef',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill the Crystalline Hunllef without making any armour within the Gauntlet.',
    id: 113,
    monster: 'Crystalline Hunllef',
    name: "Defence Doesn't Matter",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Complete the Gauntlet in less than 5 minutes.',
    id: 117,
    monster: 'Crystalline Hunllef',
    name: 'Gauntlet Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Hespori in less than 36 seconds.',
    id: 128,
    monster: 'Hespori',
    name: 'Hespori Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Alchemical Hydra 150 times.',
    id: 136,
    monster: 'Alchemical Hydra',
    name: 'Alchemical Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Alchemical Hydra without being hit by the acid pool attack.',
    id: 137,
    monster: 'Alchemical Hydra',
    name: 'Unrequired Antipoisons',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Alchemical Hydra without being hit by the lightning attack.',
    id: 138,
    monster: 'Alchemical Hydra',
    name: 'Lightning Lure',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Alchemical Hydra without being hit by the flame wall attack.',
    id: 139,
    monster: 'Alchemical Hydra',
    name: "Don't Flame Me",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Alchemical Hydra without empowering it.',
    id: 140,
    monster: 'Alchemical Hydra',
    name: 'Mixing Correctly',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Alchemical Hydra without letting it spawn a flame wall attack.',
    id: 141,
    monster: 'Alchemical Hydra',
    name: 'The Flame Skipper',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Alchemical Hydra without taking any damage.',
    id: 142,
    monster: 'Alchemical Hydra',
    name: 'Alcleanical Hydra',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill the Alchemical Hydra in less than 1 minute 45 seconds.',
    id: 144,
    monster: 'Alchemical Hydra',
    name: 'Alchemical Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Alchemical Hydra 15 times without leaving the room.',
    id: 146,
    monster: 'Alchemical Hydra',
    name: 'Working Overtime',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Stamina',
  },
  {
    description: 'Complete the Fight Caves 5 times.',
    id: 148,
    monster: 'TzTok-Jad',
    name: 'Fight Caves Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Fight caves without letting any of the Yt-MejKot heal.',
    id: 150,
    monster: 'TzTok-Jad',
    name: 'Denying the Healers',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Fight Caves without being attacked by a Tz-Kih.',
    id: 152,
    monster: 'TzTok-Jad',
    name: "You Didn't Say Anything About a Bat",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Fight Caves in less than 30 minutes.',
    id: 155,
    monster: 'TzTok-Jad',
    name: 'Fight Caves Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Kraken 100 times in a private instance without leaving the room.',
    id: 172,
    monster: 'Kraken',
    name: 'One Hundred Tentacles',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Stamina',
  },
  {
    description: 'Kill The Nightmare 50 times.',
    id: 185,
    monster: 'The Nightmare',
    name: 'Nightmare Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description:
      "Kill the Nightmare without any player taking damage from the following attacks: Nightmare rifts, an un-cured parasite explosion, Corpse flowers or the Nightmare's Surge. Also, no player can take damage off prayer or have their attacks slowed by the Nightmare spores.",
    id: 188,
    monster: 'The Nightmare',
    name: 'Perfect Nightmare',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Defeat the Nightmare (Solo) in less than 19 minutes.',
    id: 192,
    monster: 'The Nightmare',
    name: 'Nightmare (Solo) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Defeat the Nightmare (5-scale) in less than 4 minutes.',
    id: 195,
    monster: 'The Nightmare',
    name: 'Nightmare (5-Scale) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill Commander Zilyana in a private instance without attacking her directly.',
    id: 215,
    monster: 'Commander Zilyana',
    name: 'Moving Collateral',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill Zulrah 150 times.',
    id: 226,
    monster: 'Zulrah',
    name: 'Zulrah Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description:
      "Kill Zulrah whilst taking no damage from the following: Snakelings, Venom Clouds, Zulrah's Green or Crimson phase.",
    id: 229,
    monster: 'Zulrah',
    name: 'Perfect Zulrah',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Zulrah in less than 1 minute, without a slayer task.',
    id: 231,
    monster: 'Zulrah',
    name: 'Zulrah Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood 75 times.',
    id: 238,
    monster: 'Theatre of Blood',
    name: 'Theatre of Blood Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Pestilent Bloat before he shuts down for the third time.',
    id: 240,
    monster: 'Theatre of Blood',
    name: 'Two-Down',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Verzik without any Nylocas being frozen and without anyone taking damage from the Nylocas.',
    id: 241,
    monster: 'Theatre of Blood',
    name: 'Pop It',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Kill Sotetseg after surviving at least 3 ball attacks without sharing the damage and without anyone dying throughout the fight.',
    id: 242,
    monster: 'Theatre of Blood',
    name: 'A Timely Snack',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Kill The Maiden of Sugadinti without anyone in the team taking damage from the following sources: Blood Spawn projectiles and Blood Spawn trails. Also, without taking damage off prayer and without letting any of the Nylocas Matomenos heal The Maiden.',
    id: 244,
    monster: 'Theatre of Blood',
    name: 'Perfect Maiden',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      'Kill the Pestilent Bloat without anyone in the team taking damage from the following sources: Pestilent flies, Falling body parts or The Pestilent Bloats stomp attack.',
    id: 245,
    monster: 'Theatre of Blood',
    name: 'Perfect Bloat',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      'Kill the Nylocas Vasilias without anyone in the team attacking any Nylocas with the wrong attack style, without letting a pillar collapse and without getting hit by any of the Nylocas Vasilias attacks whilst off prayer.',
    id: 246,
    monster: 'Theatre of Blood',
    name: 'Perfect Nylocas',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      "Kill Sotetseg without anyone in the team stepping on the wrong tile in the maze, without getting hit by the tornado and without taking any damage from Sotetseg's attacks whilst off prayer.",
    id: 247,
    monster: 'Theatre of Blood',
    name: 'Perfect Sotetseg',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      "Kill Xarpus without anyone in the team taking any damage from Xarpus' attacks and without letting an exhumed heal Xarpus more than twice.",
    id: 248,
    monster: 'Theatre of Blood',
    name: 'Perfect Xarpus',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      "Defeat Verzik Vitur without anyone in the team taking damage from Verzik Vitur's attacks other than her spider form's correctly prayed against regular magical and ranged attacks.",
    id: 249,
    monster: 'Theatre of Blood',
    name: 'Perfect Verzik',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill The Maiden of Sugadinti without anyone in the team losing any prayer points.',
    id: 250,
    monster: 'Theatre of Blood',
    name: "Can't Drain This",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill Xarpus without anyone in the team using a ranged or magic weapon.',
    id: 251,
    monster: 'Theatre of Blood',
    name: 'Can You Dance?',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Complete the Theatre of Blood without any member of the team equipping a Scythe of Vitur.',
    id: 253,
    monster: 'Theatre of Blood',
    name: 'Back in My Day...',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Complete the Theatre of Blood (Trio) in less than 20 minutes.',
    id: 255,
    monster: 'Theatre of Blood',
    name: 'Theatre (Trio) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood (4-scale) in less than 17 minutes.',
    id: 257,
    monster: 'Theatre of Blood',
    name: 'Theatre (4-Scale) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood (5-scale) in less than 16 minutes.',
    id: 259,
    monster: 'Theatre of Blood',
    name: 'Theatre (5-Scale) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill Vorkath 100 times.',
    id: 269,
    monster: 'Vorkath',
    name: 'Vorkath Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description:
      'Hit Vorkath 12 times during the acid special without getting hit by his rapid fire or the acid pools.',
    id: 270,
    monster: 'Vorkath',
    name: 'The Walk',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Kill Vorkath 5 times without taking any damage from his special attacks and without leaving his area.',
    id: 272,
    monster: 'Vorkath',
    name: 'Dodging the Dragon',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Vorkath in less than 1 minute and 15 seconds.',
    id: 276,
    monster: 'Vorkath',
    name: 'Vorkath Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill Vorkath 10 times without leaving his area.',
    id: 278,
    monster: 'Vorkath',
    name: 'Extended Encounter',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Stamina',
  },
  {
    description: 'Complete the Chambers of Xeric: Challenge Mode 10 times.',
    id: 288,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge mode raid without anyone dying.',
    id: 290,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Immortal Raid Team',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Complete a Chambers of Xeric Challenge mode (Solo) raid without dying.',
    id: 291,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Immortal Raider',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge Mode (Solo) in less than 45 minutes.',
    id: 293,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM (Solo) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge Mode (5-scale) in less than 30 minutes.',
    id: 295,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM (5-Scale) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric: Challenge Mode (Trio) in less than 35 minutes.',
    id: 297,
    monster: 'Chambers of Xeric: Challenge Mode',
    name: 'Chambers of Xeric: CM (Trio) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete the Chambers of Xeric 75 times.',
    id: 300,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Clear the Tightrope room without Killing any Deathly Mages or Deathly Rangers.',
    id: 304,
    monster: 'Chambers of Xeric',
    name: 'No Time for Death',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete a Chambers of Xeric solo raid with more than 40,000 points.',
    id: 305,
    monster: 'Chambers of Xeric',
    name: 'Putting It Olm on the Line',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Kill the Great Olm in a solo raid without letting him use any of the following special attacks in his second to last phase: Crystal Burst, Lightning Walls, Teleportation Portals or left-hand autohealing.',
    id: 306,
    monster: 'Chambers of Xeric',
    name: 'A Not So Special Lizard',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Vasa Nistirio before he performs his teleport attack for the second time.',
    id: 309,
    monster: 'Chambers of Xeric',
    name: 'Stop Drop and Roll',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Tekton before he returns to his anvil for a second time after the fight begins.',
    id: 310,
    monster: 'Chambers of Xeric',
    name: 'Anvil No More',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete a Chambers of Xeric solo raid without dying.',
    id: 313,
    monster: 'Chambers of Xeric',
    name: 'Undying Raider',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Clear the Crystal Crabs room without wasting an orb after the first crystal has been activated.',
    id: 315,
    monster: 'Chambers of Xeric',
    name: 'Playing with Lasers',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      'Kill the Great Olm in a solo raid without taking damage from any of the following: Teleport portals, Fire Walls, Healing pools, Crystal Bombs, Crystal Burst or Prayer Orbs. You also cannot let his claws regenerate or take damage from the same acid pool back to back.',
    id: 317,
    monster: 'Chambers of Xeric',
    name: 'Perfect Olm (Solo)',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      'Kill the Great Olm in a trio raid without any team member taking damage from any of the following: Teleport portals, Fire Walls, Healing pools, Crystal Bombs, Crystal Burst or Prayer Orbs. You also cannot let his claws regenerate or take damage from the same acid pool back to back.',
    id: 318,
    monster: 'Chambers of Xeric',
    name: 'Perfect Olm (Trio)',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Tekton without taking any damage.',
    id: 319,
    monster: 'Chambers of Xeric',
    name: 'Blind Spot',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Complete a Chambers of Xeric (Solo) in less than 21 minutes.',
    id: 322,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric (Solo) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric (5-scale) in less than 15 minutes.',
    id: 324,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric (5-Scale) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete a Chambers of Xeric (Trio) in less than 16 minutes and 30 seconds.',
    id: 326,
    monster: 'Chambers of Xeric',
    name: 'Chambers of Xeric (Trio) Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill Tzkal-Zuk without letting a pillar fall before wave 67.',
    id: 346,
    monster: 'TzKal-Zuk',
    name: 'Nibblers, Begone!',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: "Complete TzHaar-Ket-Rak's fourth challenge.",
    id: 362,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: 'The IV Jad Challenge',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: "Complete TzHaar-Ket-Rak's third challenge in less than 3 minutes.",
    id: 365,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: "TzHaar-Ket-Rak's Speed-Chaser",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: "Complete TzHaar-Ket-Rak's fourth challenge with only melee.",
    id: 368,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: 'Facing Jad Head-on IV',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: "Complete TzHaar-Ket-Rak's third challenge without having anything in your inventory.",
    id: 369,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: "Supplies? Who Needs 'em?",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: "Complete TzHaar-Ket-Rak's third challenge while using a different attack style for each JalTok-Jad.",
    id: 371,
    monster: "TzHaar-Ket-Rak's Challenges",
    name: 'Multi-Style Specialist',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Theatre of Blood: Hard Mode within the challenge time.',
    id: 381,
    monster: 'Theatre of Blood: Hard Mode',
    name: 'Hard Mode? Completed It',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Complete the Theatre of Blood: Entry Mode in less than 17 minutes.',
    id: 396,
    monster: 'Theatre of Blood: Entry Mode',
    name: 'Theatre of Blood: SM Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: "Kill Phosani's Nightmare 5 times.",
    id: 401,
    monster: "Phosani's Nightmare",
    name: "Phosani's Master",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: "Kill Phosani's Nightmare within 7 minutes and 30 seconds.",
    id: 404,
    monster: "Phosani's Nightmare",
    name: "Phosani's Speedchaser",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: "Kill Phosani's Nightmare while killing every parasite and husk in one hit.",
    id: 406,
    monster: "Phosani's Nightmare",
    name: 'Crush Hour',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: "Kill Phosani's Nightmare without allowing your prayer to be disabled.",
    id: 407,
    monster: "Phosani's Nightmare",
    name: 'I Would Simply React',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: "Kill Phosani's Nightmare without a sleepwalker reaching her during her desperation phase.",
    id: 408,
    monster: "Phosani's Nightmare",
    name: 'Dreamland Express',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Nex 25 times.',
    id: 411,
    monster: 'Nex',
    name: 'Nex Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill Nex without letting her heal from her Blood Siphon special attack.',
    id: 413,
    monster: 'Nex',
    name: 'A siphon will solve this',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Nex without anyone taking damage from any Ice special attack.',
    id: 414,
    monster: 'Nex',
    name: 'Contain this!',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Nex without anyone being hit by the Smoke Dash special attack.',
    id: 415,
    monster: 'Nex',
    name: 'There is no escape!',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Nex with three or less players at the start of the fight.',
    id: 416,
    monster: 'Nex',
    name: 'Nex Trio',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill Nex without anyone being hit by the Shadow Smash attack.',
    id: 420,
    monster: 'Nex',
    name: 'Shadows Move...',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Tombs of Amascut (normal) within 18 mins at any group size.',
    id: 421,
    monster: 'Tombs of Amascut',
    name: 'Tombs Speed Runner',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description:
      'Complete a full Tombs of Amascut raid only using supplies given inside the tomb and without anyone dying.',
    id: 424,
    monster: 'Tombs of Amascut',
    name: 'You are not prepared',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description:
      'Complete the Tombs of Amascut with the "On a diet" and "Dehydration" invocations activated and without anyone dying.',
    id: 426,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Resourceful Raider',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description:
      'Complete the Tombs of Amascut without anyone in your party wearing or holding any equipment at tier 75 or above.',
    id: 427,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'But... Damage',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Defeat Zebak using only melee attacks and without dying yourself.',
    id: 428,
    monster: 'Tombs of Amascut',
    name: 'Chompington',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      "Complete phase three of The Wardens in a group of two or more, using only melee attacks and without dying yourself. The 'Insanity' invocation must be activated.",
    id: 429,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Fancy feet',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description:
      "Complete Akkha in a group of two or more, without anyone taking any damage from the following: Akkha's attacks off-prayer, Akkha's special attacks (orbs, memory, detonate), exploding shadow timers, orbs in the enrage phase or attacking Akkha with the wrong style. You must have all Akkha invocations activated.",
    id: 433,
    monster: 'Tombs of Amascut',
    name: 'Perfect Akkha',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      "Defeat Ba-Ba in a group of two or more, without anyone taking any damage from the following: Ba-Ba's Attacks off-prayer, Ba-Ba's slam, rolling boulders, rubble attack or falling rocks. No sarcophagi may be opened. You must have all Ba-Ba invocations activated.",
    id: 436,
    monster: 'Tombs of Amascut',
    name: 'Perfect Ba-Ba',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      "Defeat Zebak without anyone taking any damage from: poison, Zebak's basic attacks off-prayer, blood spawns and waves. You also must not push more than two jugs on the roar attack during the fight (you may destroy stationary ones). You must have all Zebak invocations activated.",
    id: 439,
    monster: 'Tombs of Amascut',
    name: 'Perfect Zebak',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Complete the Scabaras room in less than a minute without anyone taking any damage from puzzles.',
    id: 441,
    monster: 'Tombs of Amascut',
    name: 'Perfect Scabaras',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      "Defeat Kephri in a group of two or more, without anyone taking any damage from the following: egg explosions, Kephri's attacks, Exploding Scarabs, Bodyguards, dung attacks. No eggs may hatch throughout the fight.",
    id: 442,
    monster: 'Tombs of Amascut',
    name: 'Perfect Kephri',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description:
      'Defeat The Wardens in a group of two or more, without anyone taking avoidable damage from the following: Warden attacks, obelisk attacks, lightning attacks in phase three, skull attack in phase three, Demi god attacks in phase three. You must have all Wardens invocations activated.',
    id: 444,
    monster: 'Tombs of Amascut',
    name: 'Perfect Wardens',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Complete the Tombs of Amascut raid at level 350 or above without anyone dying.',
    id: 447,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Something of an expert myself',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Ba-Ba with all Ba-Ba invocations activated and the path levelled up to at least four, without dying yourself.',
    id: 453,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Ba-Bananza',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Zebak with all Zebak invocations activated and the path levelled up to at least four, without dying yourself.',
    id: 455,
    monster: 'Tombs of Amascut: Expert Mode',
    name: "Rockin' around the croc",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat Kephri with all Kephri invocations activated and the path levelled up to at least four, without dying yourself.',
    id: 456,
    monster: 'Tombs of Amascut: Expert Mode',
    name: "Doesn't bug me",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      "Defeat Kephri without letting her heal above 25% after the first down. The 'Medic' invocation must be activated. You must do this without dying yourself.",
    id: 457,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'All out of medics',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      "Defeat Elidinis' Warden in phase three of the Wardens fight with 'Aerial Assault', 'Stay vigilant' and 'Insanity' invocations activated and without dying yourself.",
    id: 459,
    monster: 'Tombs of Amascut',
    name: "Better get movin'",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description:
      'Defeat the Wardens with all Wardens invocations activated, at expert level and without dying yourself.',
    id: 460,
    monster: 'Tombs of Amascut: Expert Mode',
    name: "Warden't you believe it",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Tombs of Amascut 25 times.',
    id: 466,
    monster: 'Tombs of Amascut',
    name: 'Tomb Looter',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Tombs of Amascut 50 times.',
    id: 467,
    monster: 'Tombs of Amascut',
    name: 'Tomb Raider',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Complete the Tombs of Amascut (Expert mode) 25 times.',
    id: 470,
    monster: 'Tombs of Amascut: Expert Mode',
    name: 'Expert Tomb Looter',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Phantom Muspah by only dealing damage to it with a salamander.',
    id: 472,
    monster: 'Phantom Muspah',
    name: 'More than just a ranged weapon',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill the Phantom Muspah 10 times in one trip.',
    id: 474,
    monster: 'Phantom Muspah',
    name: 'Essence Farmer',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Stamina',
  },
  {
    description: 'Kill the Phantom Muspah in less than 2 minutes without a slayer task.',
    id: 476,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Phantom Muspah 50 times.',
    id: 480,
    monster: 'Phantom Muspah',
    name: 'Phantom Muspah Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Phantom Muspah whilst it is surrounded by spikes.',
    id: 481,
    monster: 'Phantom Muspah',
    name: 'Space is Tight',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Phantom Muspah without taking any avoidable damage.',
    id: 483,
    monster: 'Phantom Muspah',
    name: 'Walk Straight Pray True',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Vardorvis in less than 1:05 without a slayer task.',
    id: 486,
    monster: 'Vardorvis',
    name: 'Vardorvis Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill Vardorvis 50 times.',
    id: 489,
    monster: 'Vardorvis',
    name: 'Vardorvis Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill Vardorvis perfectly 5 times without leaving.',
    id: 491,
    monster: 'Vardorvis',
    name: 'Perfect Vardorvis',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Vardorvis with gear worth 2m or less in total.',
    id: 493,
    monster: 'Vardorvis',
    name: 'Budget Cutter',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill the Whisperer in less than 2:25 without a slayer task.',
    id: 495,
    monster: 'Whisperer',
    name: 'Whisperer Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Whisperer 50 times.',
    id: 498,
    monster: 'Whisperer',
    name: 'Whisperer Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Whisperer without taking avoidable damage 5 times without leaving.',
    id: 500,
    monster: 'Whisperer',
    name: 'Perfect Whisperer',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill the Leviathan in less than 1:25 without a slayer task.',
    id: 504,
    monster: 'Leviathan',
    name: 'Leviathan Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill the Leviathan 50 times.',
    id: 507,
    monster: 'Leviathan',
    name: 'Leviathan Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Leviathan perfectly 5 times without leaving.',
    id: 509,
    monster: 'Leviathan',
    name: 'Perfect Leviathan',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill the Leviathan without stunning the boss more than once.',
    id: 510,
    monster: 'Leviathan',
    name: 'Serpentine Solo',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Duke Sucellus in less than 50 seconds without a slayer task.',
    id: 513,
    monster: 'Duke Sucellus',
    name: 'Duke Sucellus Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill Duke Sucellus 50 times.',
    id: 516,
    monster: 'Duke Sucellus',
    name: 'Duke Sucellus Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill Duke Sucellus without taking any avoidable damage 5 times without leaving.',
    id: 518,
    monster: 'Duke Sucellus',
    name: 'Perfect Duke Sucellus',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Duke Sucellus without taking any avoidable damage, whilst also never running.',
    id: 519,
    monster: 'Duke Sucellus',
    name: 'Cold Feet',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Defeat Sol Heredit once.',
    id: 538,
    monster: 'Fortis Colosseum',
    name: 'Sportsmanship',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Defeat Sol Heredit using only a Spear, Hasta or Halberd.',
    id: 540,
    monster: 'Fortis Colosseum',
    name: 'I Brought Mine Too',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description:
      'Defeat Sol Heredit after using Fortis Salute to the north, east, south and west of the arena while he is below 10% hitpoints.',
    id: 544,
    monster: 'Fortis Colosseum',
    name: 'Showboating',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: "Complete Wave 11 with either 'Red Flag', 'Dynamic Duo', or 'Doom II' active.",
    id: 546,
    monster: 'Fortis Colosseum',
    name: 'One-off',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Complete the Colosseum with a total time of 28:00 or less.',
    id: 549,
    monster: 'Fortis Colosseum',
    name: 'Colosseum Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Kill three Tormented Demons within 3 seconds.',
    id: 554,
    monster: 'Tormented Demon',
    name: 'Three Times the Thrashing',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill Araxxor 75 times.',
    id: 557,
    monster: 'Araxxor',
    name: 'Araxxor Master',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Kill Araxxor 5 times in 10:00.',
    id: 559,
    monster: 'Araxxor',
    name: 'Araxxor Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description:
      "Kill Araxxor perfectly, without taking damage from Araxxor's Mage & Range attacks, melee attack off prayer, araxyte minions damage, or damage from acid pools.",
    id: 561,
    monster: 'Araxxor',
    name: 'Perfect Araxxor',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Perfection',
  },
  {
    description: 'Kill Araxxor without ever having venom or poison immunity.',
    id: 563,
    monster: 'Araxxor',
    name: 'Let it seep in',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Have an Araxyte kill three other Araxytes.',
    id: 566,
    monster: 'Araxxor',
    name: 'Araxyte Betrayal',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Kill Araxxor 10 times without leaving.',
    id: 567,
    monster: 'Araxxor',
    name: 'Arachnid Lover',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Stamina',
  },
  {
    description: 'Kill the Hueycoatl using only dragonbane weaponry.',
    id: 573,
    monster: 'The Hueycoatl',
    name: 'Is it a bird?',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Kill the Hueycoatl in 2:30 with five or fewer players.',
    id: 577,
    monster: 'The Hueycoatl',
    name: 'Hueycoatl Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description: 'Defeat Yama 50 times.',
    id: 600,
    monster: 'Yama',
    name: 'Yama Veteran',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Defeat Yama in an average time of under 3:00 over your last four kills.',
    id: 602,
    monster: 'Yama',
    name: 'Yama Speed-Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
  {
    description:
      'Defeat Yama without anybody healing using anything other than plain pizza and without anybody drinking any potions.',
    id: 604,
    monster: 'Yama',
    name: 'No toppings, no drinks, thanks',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description:
      'Defeat Yama without getting hit by shadows and without being more than one tile away from the center of his shadow crash attack.',
    id: 605,
    monster: 'Yama',
    name: 'Shadow dancer',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Defeat Yama without getting hit by fire and having only killed void flares with special attacks.',
    id: 606,
    monster: 'Yama',
    name: 'Fire fighter',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl at delve level 8.',
    id: 611,
    monster: 'Doom of Mokhaiotl',
    name: 'Doom Veteran',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Kill Count',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl at level 8 or above before he finishes the first burrow phase.',
    id: 614,
    monster: 'Doom of Mokhaiotl',
    name: 'Mokhaiotl Drift',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 without ever letting a grub be absorbed.',
    id: 615,
    monster: 'Doom of Mokhaiotl',
    name: 'Grub Patrol',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Mechanical',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 whilst always wearing a shield.',
    id: 620,
    monster: 'Doom of Mokhaiotl',
    name: "Mine's Better",
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Restriction',
  },
  {
    description: 'Defeat the Doom of Mokhaiotl levels 1-8 in less than 10:00.',
    id: 622,
    monster: 'Doom of Mokhaiotl',
    name: 'Doom Chaser',
    points: 5,
    tier: CombatAchievementTier.Master,
    type: 'Speed',
  },
];
