import { CombatAchievementTask, CombatAchievementTier } from '../CombatAchievement';

/**
 * Medium-tier Combat Achievement tasks, authored directly in TypeScript.
 *
 * Source: https://oldschool.runescape.wiki/w/Combat_Achievements/Medium
 */
export const MEDIUM_COMBAT_ACHIEVEMENTS: CombatAchievementTask[] = [
  {
    description: 'Open the Barrows chest 25 times.',
    id: 25,
    monster: 'Barrows',
    name: 'Barrows Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dharok, Verac, Torag and Guthan without letting them attack you with melee.',
    id: 26,
    monster: 'Barrows',
    name: "Can't Touch Me",
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description:
      'Kill all six Barrows Brothers and loot the Barrows chest without taking any damage from any of the brothers.',
    id: 27,
    monster: 'Barrows',
    name: 'Pray for Success',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill a Brutal Black Dragon.',
    id: 34,
    monster: 'Brutal Black Dragon',
    name: 'Brutal, Big, Black and Firey',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: "Open Bryophyta's chest 5 times.",
    id: 36,
    monster: 'Bryophyta',
    name: 'Bryophyta Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: "Kill all 3 of Bryophyta's growthlings within 3 seconds of the first one dying.",
    id: 38,
    monster: 'Bryophyta',
    name: 'Quick Cutter',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill Skotizo once.',
    id: 44,
    monster: 'Skotizo',
    name: 'Skotizo Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Skotizo with no altars active.',
    id: 46,
    monster: 'Skotizo',
    name: 'Demonic Weakening',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill Skotizo with a demonbane weapon equipped.',
    id: 48,
    monster: 'Skotizo',
    name: 'Demonbane Weaponry',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Kill the Chaos Fanatic 10 times.',
    id: 61,
    monster: 'Chaos Fanatic',
    name: 'Chaos Fanatic Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Chaos Fanatic without anyone being hit by his explosion attack.',
    id: 63,
    monster: 'Chaos Fanatic',
    name: 'Sorry, What Was That?',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill the Crazy Archaeologist 10 times.',
    id: 70,
    monster: 'Crazy Archaeologist',
    name: 'Crazy Archaeologist Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Crazy Archaeologist with only magical attacks.',
    id: 72,
    monster: 'Crazy Archaeologist',
    name: 'Mage of the Ruins',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Crazy Archaeologist without anyone being hit by his "Rain of Knowledge" attack.',
    id: 73,
    monster: 'Crazy Archaeologist',
    name: "I'd Rather Not Learn",
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill the Deranged Archaeologist 25 times.',
    id: 77,
    monster: 'Deranged Archaeologist',
    name: 'Deranged Archaeologist Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Deranged Archaeologist with only magical attacks.',
    id: 78,
    monster: 'Deranged Archaeologist',
    name: 'Mage of the Swamp',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Deranged Archaeologist without anyone being hit by his "Learn to Read" attack.',
    id: 79,
    monster: 'Deranged Archaeologist',
    name: "I'd Rather Be Illiterate",
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill a Gargoyle.',
    id: 97,
    monster: 'Gargoyle',
    name: 'A Smashing Time',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: "Open Obor's chest 5 times.",
    id: 130,
    monster: 'Obor',
    name: 'Obor Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Obor without being pushed back more than one square by his knockback attack.',
    id: 132,
    monster: 'Obor',
    name: 'Back to the Wall',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill Obor without taking any damage off prayer.',
    id: 133,
    monster: 'Obor',
    name: 'Squashing the Giant',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill the King Black Dragon 25 times.',
    id: 163,
    monster: 'King Black Dragon',
    name: 'King Black Dragon Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the King Black Dragon with the Protect from Melee prayer activated.',
    id: 164,
    monster: 'King Black Dragon',
    name: 'Claw Clipper',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill the King Black Dragon with a stab weapon.',
    id: 165,
    monster: 'King Black Dragon',
    name: 'Hide Penetration',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Kill the King Black Dragon with an antifire potion active and an antidragon shield equipped.',
    id: 166,
    monster: 'King Black Dragon',
    name: 'Antifire Protection',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Kill a Kurask.',
    id: 173,
    monster: 'Kurask',
    name: 'Master of Broad Weaponry',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Giant mole 25 times.',
    id: 178,
    monster: 'Giant Mole',
    name: 'Giant Mole Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Giant Mole without her damaging anyone.',
    id: 182,
    monster: 'Giant Mole',
    name: 'Avoiding Those Little Arms',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill Dagannoth Prime 10 times.',
    id: 197,
    monster: 'Dagannoth Prime',
    name: 'Dagannoth Prime Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dagannoth Rex 10 times.',
    id: 201,
    monster: 'Dagannoth Rex',
    name: 'Dagannoth Rex Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dagannoth Rex whilst he is immobilized.',
    id: 204,
    monster: 'Dagannoth Rex',
    name: 'A Frozen King',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill Sarachnis 25 times.',
    id: 207,
    monster: 'Sarachnis',
    name: 'Sarachnis Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Sarachnis with a crush weapon.',
    id: 210,
    monster: 'Sarachnis',
    name: 'Newspaper Enthusiast',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Kill a Skeletal Wyvern',
    id: 223,
    monster: 'Skeletal Wyvern',
    name: 'A Frozen Foe from the Past',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Dagannoth Supreme 10 times.',
    id: 233,
    monster: 'Dagannoth Supreme',
    name: 'Dagannoth Supreme Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Subdue the Wintertodt 10 times.',
    id: 280,
    monster: 'Wintertodt',
    name: 'Wintertodt Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Subdue the Wintertodt without allowing all 4 braziers to be broken at the same time.',
    id: 283,
    monster: 'Wintertodt',
    name: 'Can We Fix It?',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Subdue the Wintertodt without any of the Pyromancers falling.',
    id: 284,
    monster: 'Wintertodt',
    name: 'Leaving No One Behind',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Subdue Tempoross 10 times.',
    id: 354,
    monster: 'Tempoross',
    name: 'Tempoross Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Subdue Tempoross alone without getting hit by any fires, torrents or waves.',
    id: 359,
    monster: 'Tempoross',
    name: 'The Lone Angler',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Deal 100 damage to creatures using undead thralls.',
    id: 399,
    monster: 'N/A',
    name: 'Sit Back and Relax',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill Scurrius 10 times.',
    id: 522,
    monster: 'Scurrius',
    name: 'Scurrius Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description:
      'Kill Scurrius in a private instance without taking damage from the following attacks: Tail Swipe and Falling Bricks. Pray correctly against the following attacks: Flying Fur and Bolts of Electricity.',
    id: 524,
    monster: 'Scurrius',
    name: 'Perfect Scurrius',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: "Kill 6 Giant Rats within Scurrius' lair in 3 seconds.",
    id: 525,
    monster: 'Scurrius',
    name: 'Efficient Pest Control',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Open the Reward Chest after defeating all three Moons.',
    id: 528,
    monster: 'Moons of Peril',
    name: 'Lunar Triplet',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Open the Reward Chest 5 times.',
    id: 529,
    monster: 'Moons of Peril',
    name: 'Perilous Novice',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Defeat all three Moons in one run by only attacking with a Dragon Scimitar.',
    id: 534,
    monster: 'Moons of Peril',
    name: 'Back to Our Roots',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Defeat all three Moons in one run in under 8 minutes.',
    id: 535,
    monster: 'Moons of Peril',
    name: 'Moons of Peril Speed-Trialist',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Speed',
  },
  {
    description: 'Kill the Hueycoatl once.',
    id: 568,
    monster: 'The Hueycoatl',
    name: 'Hueycoatl Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Hueycoatl using only earth spells.',
    id: 574,
    monster: 'The Hueycoatl',
    name: "You're a wizard",
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Kill Amoxliatl once.',
    id: 579,
    monster: 'Amoxliatl',
    name: 'Amoxliatl Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Amoxliatl using only glacial temotli as a weapon.',
    id: 584,
    monster: 'Amoxliatl',
    name: 'Temotli Triumph',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Restriction',
  },
  {
    description: 'Kill the Royal Titans 10 times.',
    id: 589,
    monster: 'Royal Titans',
    name: 'Royal Titan Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Royal Titans 25 times.',
    id: 590,
    monster: 'Royal Titans',
    name: 'Royal Titan Adept',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description:
      'Kill both Royal Titans while they are charging up their area attack. Both titans must die during the same charging phase.',
    id: 598,
    monster: 'Royal Titans',
    name: 'It takes too long',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Mechanical',
  },
  {
    description: 'Kill the Shellbane Gryphon 50 times.',
    id: 626,
    monster: 'Shellbane gryphon',
    name: 'Shellbane Veteran',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill the Shellbane Gryphon without taking damage.',
    id: 627,
    monster: 'Shellbane gryphon',
    name: 'Perfect Shellbane',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
  {
    description: 'Kill the Shellbane Gryphon 10 times within 12:30 minutes of entering the cave.',
    id: 628,
    monster: 'Shellbane gryphon',
    name: 'Shellbane Speedrunner',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Speed',
  },
  {
    description: 'Kill Brutus 10 times.',
    id: 633,
    monster: 'Brutus',
    name: 'Brutus Champion',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Kill Count',
  },
  {
    description: 'Kill Brutus whilst neither equipping nor consuming anything.',
    id: 635,
    monster: 'Brutus',
    name: 'Beef vs Beef',
    points: 2,
    tier: CombatAchievementTier.Medium,
    type: 'Perfection',
  },
];
