import { Npc } from '../Npc';
import { NpcDrop } from '../NpcDrop';

export const manDrops: NpcDrop[] = [
  new NpcDrop('Bones', 1, 'Always'),
  new NpcDrop('Coins', 3, '1/3.368'),
  new NpcDrop('Coins', 10, '23/128'),
  new NpcDrop('Coins', 5, '9/128'),
  new NpcDrop('Coins', 15, '4/128'),
  new NpcDrop('Coins', 25, '1/128'),
  new NpcDrop('Bronze med helm', 1, '1/64'),
  new NpcDrop('Iron dagger', 1, '1/128'),
  new NpcDrop('Bronze bolts', [2, 12], '22/128'),
  new NpcDrop('Bronze arrow', 7, '3/128'),
  new NpcDrop('Earth rune', 4, '2/128'),
  new NpcDrop('Fire rune', 6, '2/128'),
  new NpcDrop('Mind rune', 9, '2/128'),
  new NpcDrop('Chaos rune', 2, '1/128'),
  new NpcDrop('Fishing bait', 1, '5/128'),
  new NpcDrop('Copper ore', 1, '2/128'),
  new NpcDrop('Earth talisman', 1, '2/128'),
  new NpcDrop('Cabbage', 1, '1/128'),
  new NpcDrop('Clue scroll (beginner)', 1, '1/90'),
  new NpcDrop('Clue scroll (easy)', 1, '1/128'),
  // Herbs drop table is rolled separately, not included here for brevity
];

export const manLocations: string[] = [
  'Lumbridge',
  'Varrock',
  'Falador',
  'Edgeville',
  'Draynor Village',
  'Al Kharid',
  'Ardougne',
  'Rimmington',
  'Catherby',

  "Seers' Village",
  'Yanille',
  'Etceteria',
  'Miscellania',
  'Port Sarim',
  'Ice Mountain',
  'Kingstown',
  'Hosidius',
  'Port Piscarilius',
  'Musa Point',
  'Fishing Guild',
  'Blue Moon Inn',
  'Jolly Boar Inn',
  'Forgotten Cemetery',
  "West of Watson's house",
  'Shayzien Styles',
];

export const Man = new Npc({
  aggressiveStats: {
    attackBonus: 1,
    magicStrengthBonus: 1,
    rangedStrengthBonus: 1,
    strengthBonus: 1,
  },
  combat: {
    attackSpeed: 0,
    attackStyles: [],
    hasWeaponVenom: false,
    isAggressive: false,
    isAttackable: true,
    isPoisonous: false,
    maxHit: 0,
    respawnTime: 0,
    weaknesses: ['Crush'],
  },
  combatLevel: 2,
  defences: {
    magic: { bonus: 0, elementalWeakness: undefined },
    melee: { crush: 0, slash: 0, stab: 0 },
    ranged: { heavy: 0, light: 0, standard: 0 },
  },
  drops: manDrops,
  examine: "One of Gielinor's many citizens.",
  id: 1,
  immunities: {
    canBeCannoned: false,
    canBePoison: false,
    canBeThralled: false,
    canBeVenom: false,
    isPoisonous: false,
  },
  locations: manLocations,
  members: false,
  name: 'Man',
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Man',
  stats: {
    attack: 1,
    defence: 1,
    hitpoints: 7,
    magic: 1,
    ranged: 1,
    strength: 1,
  },
});

export default Man;
