//  List of all old school runescape quests

export const QuestList: string[] = [
  'A Kingdom Divided',
  'A Night at the Theatre',
  'A Porcine of Interest',
  "A Soul's Bane",
  'A Tail of Two Cats',
  'A Taste of Hope',
  "Alfred Grimhand's Barcrawl",
  'Animal Magnetism',
  'Another Slice of H.A.M.',
  'At First Light',
  'Ascent of Arceuus',
  'Below Ice Mountain',
  'Beneath Cursed Sands',
  'Between a Rock...',
  'Big Chompy Bird Hunting',
  'Biohazard',
  "Black Knights' Fortress",
  'Bone Voyage',
  'Cabin Fever',
  'Children of the Sun',
  'Client of Kourend',
  'Clock Tower',
  'Cold War',
  'Contact!',
  "Cook's Assistant",
  'Creature of Fenkenstrain',
  'Curse of the Empty Lord',
  "Daddy's Home",
  'Darkness of Hallowvale',
  'Death on the Isle',
  'Death Plateau',
  'Death to the Dorgeshuun',
  'Defender of Varrock',
  'Demon Slayer',
  'Desert Treasure I',
  'Desert Treasure II - The Fallen Empire',
  'Devious Minds',
  "Doric's Quest",
  'Dragon Slayer I',
  'Dragon Slayer II',
  'Dream Mentor',
  'Druidic Ritual',
  'Dwarf Cannon',
  "Eadgar's Ruse",
  "Eagles' Peak",
  'Elemental Workshop I',
  'Elemental Workshop II',
  "Enakhra's Lament",
  'Enlightened Journey',
  'Enter the Abyss',
  'Ernest the Chicken',
  'Ethically Acquired Antiquities',
  'Fairytale I - Growing Pains',
  'Fairytale II - Cure a Queen',
  'Family Crest',
  'Family Pest',
  'Fight Arena',
  'Fishing Contest',
  'Forgettable Tale...',
  'The Fremennik Isles',
  'The Fremennik Trials',
  'The Garden of Death',
  'The Giant Dwarf',
  'The Golem',
  'The Grand Tree',
  'The Great Brain Robbery',
  'The Hand in the Sand',
  'The Heart of Darkness',
  'The Lost Tribe',
  'The Path of Glouphrie',
  'The Queen of Thieves',
  'The Restless Ghost',
  'The Ribbiting Tale of a Lily Pad Labour Dispute',
  'The Slug Menace',
  'The Tale of the Righteous',
  'The Temple of Ikov',
  'The Tourist Trap',
  'The Underground Pass',
  'Tower of Life',
  'Tree Gnome Village',
  'Troll Romance',
  'Troll Stronghold',
  "Twilight's Promise",
  'Vampyre Slayer',
  'Wanted!',
  'Watchtower',
  'Waterfall Quest',
  'What Lies Below',
  'While Guthix Sleeps',
  "Witch's House",
  "Witch's Potion",
  'X Marks the Spot',
  'Zogre Flesh Eaters',
];
