import { Item } from './Item';

export const Bones = Item.fromJson({
  destroy: 'Drop',
  equipable: false,
  examine: 'A pile of bones.',
  highAlch: 750,
  iconUrl: 'https://oldschool.runescape.wiki/images/thumb/2/27/Bones_detail.png/120px-Bones_detail.png',
  id: 526,
  lowAlch: 500,
  members: false,
  name: 'Bones',
  noted: false,
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Bones',
  questItem: false,
  releaseDate: '2005-11-15',
  stackable: false,
  tradeable: true,
  value: 1000,
  weight: 0,
});

export const Coins = Item.fromJson({
  destroy: 'Drop',
  equipable: false,
  examine: 'A pile of coins.',
  highAlch: 750,
  iconUrl: 'https://oldschool.runescape.wiki/images/thumb/8/8e/Coins_detail.png/120px-Coins_detail.png',
  id: 995,
  lowAlch: 500,
  members: false,
  name: 'Coins',
  noted: false,
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Coins',
  questItem: false,
  releaseDate: '2005-11-15',
  stackable: false,
  tradeable: true,
  value: 1000,
  weight: 0,
});

export const BucketOfWater = Item.fromJson({
  destroy: 'Drop',
  equipable: false,
  examine: 'A bucket of water.',
  highAlch: 750,
  iconUrl:
    'https://oldschool.runescape.wiki/images/thumb/3/3a/Bucket_of_water_detail.png/120px-Bucket_of_water_detail.png',
  id: 1929,
  lowAlch: 500,
  members: false,
  name: 'Bucket of water',
  noted: false,
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Bucket_of_water',
  questItem: false,
  releaseDate: '2005-11-15',
  stackable: false,
  tradeable: true,
  value: 1000,
  weight: 0,
});
