import { Item, ItemJson } from '../Item';

const ancientStaffData: ItemJson = {
  attackCrush: 10,
  attackMagic: 15,
  attackRanged: 0,
  attackSlash: -1,
  attackStab: 2,
  defenceCrush: 2,
  defenceMagic: 15,
  defenceRanged: 0,
  defenceSlash: 3,
  defenceStab: 2,
  destroy: 'Drop',
  equipable: true,
  examine: 'A staff of the ancient magicks.',
  highAlch: 48000,
  id: 4675,
  lowAlch: 32000,
  magicDamage: 0,
  members: true,
  meleeStrength: 0,
  name: 'Ancient staff',
  noted: false,
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Ancient_staff',
  prayer: 1,
  questItem: false,
  releaseDate: '4 January 2007',
  stackable: false,
  tradeable: true,
  value: 80000,
  weight: 2.267,
};

export const AncientStaff = Item.fromJson(ancientStaffData);
