import { LeagueRegion, NotableDrop } from '../model';

/**
 * Represents an area in the Demonic Pacts League, which is a specific region of the game world that has its own unique content, mechanics, and rewards during the league. Each area includes information about its name, description, whether it is a starting area, its accessibility, any tasks required to unlock it, notable settlements and activities within the area, any echo bosses that can be found there, quests and achievements that are automatically completed upon entering the area, and notable drops that can be obtained from activities within the area. This type is used to organize and reference the different areas of the Demonic Pacts League in a structured way.
 */
export interface DemonicPactsLeagueArea {
  name: string;
  description: string;
  isStarting: boolean;
  isAccessible: boolean;
  unlocksAfterTasks?: number;
  notableSettlements: string[];
  notableActivities: string[];
  echoBoss?: string;
  autoCompletedQuests: string[];
  autoCompletedAchievements: string[];
  notableDrops?: NotableDrop[];
}

/**
 * A record of the different areas in the Demonic Pacts League, keyed by a unique identifier for each area (e.g., "varlamore", "karamja", "asgarnia"). Each entry in the record contains all the relevant information about that area, as defined by the DemonicPactsLeagueArea interface. This structure allows for easy retrieval and reference of area information throughout the application, particularly when displaying league content or calculating rewards and progress for players participating in the Demonic Pacts League.
 */
export const DEMONIC_PACTS_LEAGUE_AREAS: Record<string, DemonicPactsLeagueArea> = {
  asgarnia: {
    autoCompletedAchievements: [],
    autoCompletedQuests: [
      "My Arm's Big Adventure",
      'Below Ice Mountain',
      'Dwarf Cannon',
      "Heroes' Quest",
      'A Porcine of Interest',
      'Sheep Shearer',
      "Cook's Assistant",
      'The Restless Ghost',
    ],
    description:
      'The Asgarnia area covers the entire Kingdom of Asgarnia along with the island of Entrana, the Pest Control islands, and Troll Country. Access to Catherby from White Wolf Mountain will be restricted by magical barriers.',
    echoBoss: 'Cerberus',
    isAccessible: true,
    isStarting: false,
    name: 'Asgarnia',
    notableActivities: ['God Wars Dungeon', 'Pest Control', 'Cerberus', 'Nex'],
    notableDrops: [
      {
        baseRarity: '1/25',
        dropMultiplier2x: 'N/A',
        dropMultiplier5x: 'N/A',
        item: 'Fang of the hound',
        source: 'Echo Cerberus',
      },
      {
        baseRarity: '1/50',
        dropMultiplier2x: '1/25',
        dropMultiplier5x: '1/10',
        item: 'Bronze through rune defenders',
        source: 'Cyclops',
      },
      {
        baseRarity: '1/100',
        dropMultiplier2x: '1/50',
        dropMultiplier5x: '1/20',
        item: 'Dragon defender',
        source: 'Cyclops',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Primordial and Pegasian crystals',
        source: 'Cerberus',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Eternal boots',
        source: 'Cerberus',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Smouldering stone',
        source: 'Cerberus',
      },
      {
        baseRarity: '1/381',
        dropMultiplier2x: '1/190',
        dropMultiplier5x: '1/76',
        item: 'Armadyl armour',
        source: "Kree'arra",
      },
      {
        baseRarity: '1/508',
        dropMultiplier2x: '1/254',
        dropMultiplier5x: '1/101',
        item: 'Armadyl hilt',
        source: "Kree'arra",
      },
      {
        baseRarity: '1/381',
        dropMultiplier2x: '1/190',
        dropMultiplier5x: '1/76',
        item: 'Bandos armour',
        source: 'General Graardor',
      },
      {
        baseRarity: '1/508',
        dropMultiplier2x: '1/254',
        dropMultiplier5x: '1/101',
        item: 'Bandos hilt',
        source: 'General Graardor',
      },
      {
        baseRarity: '1/127',
        dropMultiplier2x: '1/63',
        dropMultiplier5x: '1/25',
        item: 'Saradomin sword',
        source: 'Commander Zilyana',
      },
      {
        baseRarity: '1/254',
        dropMultiplier2x: '1/127',
        dropMultiplier5x: '1/50',
        item: "Saradomin's light",
        source: 'Commander Zilyana',
      },
      {
        baseRarity: '1/508',
        dropMultiplier2x: '1/254',
        dropMultiplier5x: '1/101',
        item: 'Armadyl crossbow',
        source: 'Commander Zilyana',
      },
      {
        baseRarity: '1/508',
        dropMultiplier2x: '1/254',
        dropMultiplier5x: '1/101',
        item: 'Saradomin hilt',
        source: 'Commander Zilyana',
      },
      {
        baseRarity: '1/127',
        dropMultiplier2x: '1/63',
        dropMultiplier5x: '1/25',
        item: 'Steam battlestaff',
        source: "K'ril Tsutsaroth",
      },
      {
        baseRarity: '1/127',
        dropMultiplier2x: '1/63',
        dropMultiplier5x: '1/25',
        item: 'Zamorakian spear',
        source: "K'ril Tsutsaroth",
      },
      {
        baseRarity: '1/508',
        dropMultiplier2x: '1/254',
        dropMultiplier5x: '1/101',
        item: 'Staff of the dead',
        source: "K'ril Tsutsaroth",
      },
      {
        baseRarity: '1/508',
        dropMultiplier2x: '1/254',
        dropMultiplier5x: '1/101',
        item: 'Zamorak hilt',
        source: "K'ril Tsutsaroth",
      },
      {
        baseRarity: '1/254',
        dropMultiplier2x: '1/127',
        dropMultiplier5x: '1/50',
        item: 'Any Godsword shard',
        source: "Kree'arra, General Graardor, Commander Zilyana, K'ril Tsutsaroth",
      },
      {
        baseRarity: '1/128',
        dropMultiplier2x: '1/64',
        dropMultiplier5x: '1/25',
        item: 'Dragon boots',
        source: 'Spiritual mages',
      },
      {
        baseRarity: '1/10,000',
        dropMultiplier2x: '1/5,000',
        dropMultiplier5x: '1/2,000',
        item: 'Draconic visage',
        source: 'Skeletal wyvern',
      },
      {
        baseRarity: '1/10,000',
        dropMultiplier2x: '1/5,000',
        dropMultiplier5x: '1/2,000',
        item: 'Draconic visage',
        source: 'Black Dragon',
      },
      {
        baseRarity: '1/172',
        dropMultiplier2x: '1/86',
        dropMultiplier5x: '1/34',
        item: 'Zaryte vambraces',
        source: 'Nex',
      },
      { baseRarity: '1/258', dropMultiplier2x: '1/129', dropMultiplier5x: '1/51', item: 'Nihil horn', source: 'Nex' },
      { baseRarity: '1/258', dropMultiplier2x: '1/129', dropMultiplier5x: '1/51', item: 'Torva armour', source: 'Nex' },
      {
        baseRarity: '1/516',
        dropMultiplier2x: '1/258',
        dropMultiplier5x: '1/103',
        item: 'Ancient hilt',
        source: 'Nex',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Bellator ring',
        source: 'The Whisperer',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Soulreaper axe pieces',
        source: 'The Whisperer',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Virtus robes',
        source: 'The Whisperer',
      },
      {
        baseRarity: '1/34',
        dropMultiplier2x: '1/17',
        dropMultiplier5x: '1/6',
        item: "Awakener's orb",
        source: 'The Whisperer',
      },
      {
        baseRarity: '1/32,768',
        dropMultiplier2x: '1/16,384',
        dropMultiplier5x: '1/6,553',
        item: 'Smouldering stone',
        source: 'Hellhounds',
      },
      {
        baseRarity: '1/16',
        dropMultiplier2x: '1/8',
        dropMultiplier5x: '1/3',
        item: 'Giantsoul amulet',
        source: 'Royal Titans',
      },
      {
        baseRarity: '1/75',
        dropMultiplier2x: '1/37',
        dropMultiplier5x: '1/15',
        item: 'Deadeye prayer scroll',
        source: 'Royal Titans',
      },
      {
        baseRarity: '1/75',
        dropMultiplier2x: '1/37',
        dropMultiplier5x: '1/15',
        item: 'Mystic vigour prayer scroll',
        source: 'Royal Titans',
      },
      {
        baseRarity: '1/75',
        dropMultiplier2x: '1/37',
        dropMultiplier5x: '1/15',
        item: 'Fire element staff crown',
        source: 'Royal Titans',
      },
      {
        baseRarity: '1/75',
        dropMultiplier2x: '1/37',
        dropMultiplier5x: '1/15',
        item: 'Ice element staff crown',
        source: 'Royal Titans',
      },
    ],
    notableSettlements: [
      'Burthorpe',
      'Dwarven Mine',
      'Falador',
      'Goblin Village',
      'God Wars Dungeon',
      'Ruins of Camdozaal',
      'Port Sarim',
      'Rimmington',
      'Taverley',
    ],
  },
  desert: {
    autoCompletedAchievements: [],
    autoCompletedQuests: [
      'Desert Treasure II',
      "Icthlarin's Little Helper",
      'Prince Ali Rescue',
      'The Golem',
      'Shadow of the Storm',
    ],
    description:
      "The Kharidian Desert area covers the entirety of the Kharidian Desert. The Emir's Arena minigame will not be available during this league, although the building itself is accessible.",
    echoBoss: 'Kalphite Queen',
    isAccessible: true,
    isStarting: false,
    name: 'Kharidian Desert',
    notableActivities: ['Tombs of Amascut', 'Kalphite Queen', 'Pyramid Plunder', 'Tempoross'],
    notableDrops: [
      {
        baseRarity: '1/20',
        dropMultiplier2x: 'N/A',
        dropMultiplier5x: 'N/A',
        item: 'Drygore blowpipe',
        source: 'Echo Kalphite Queen',
      },
      {
        baseRarity: '1/128',
        dropMultiplier2x: '1/64',
        dropMultiplier5x: '1/25',
        item: 'Kq head',
        source: 'Kalphite Queen',
      },
      {
        baseRarity: '1/50',
        dropMultiplier2x: '1/25',
        dropMultiplier5x: '1/10',
        item: 'All unique rewards',
        source: 'Tombs of Amascut',
      },
      {
        baseRarity: '1/63',
        dropMultiplier2x: '1/31',
        dropMultiplier5x: '1/12',
        item: "Pharaoh's sceptre",
        source: 'Pyramid plunder',
      },
      {
        baseRarity: '1/128',
        dropMultiplier2x: '1/64',
        dropMultiplier5x: '1/25',
        item: 'Dragon chainbody',
        source: 'Kalphite Queen',
      },
      {
        baseRarity: '1/400',
        dropMultiplier2x: '1/200',
        dropMultiplier5x: '1/80',
        item: 'Dragon pickaxe',
        source: 'Kalphite Queen',
      },
      {
        baseRarity: '1/32,768',
        dropMultiplier2x: '1/16,384',
        dropMultiplier5x: '1/6,553',
        item: 'Dragon chainbody',
        source: 'Dust devil',
      },
      {
        baseRarity: '1/256',
        dropMultiplier2x: '1/128',
        dropMultiplier5x: '1/51',
        item: 'Dragon 2h sword',
        source: 'Kalphite Queen',
      },
      {
        baseRarity: '1/768',
        dropMultiplier2x: '1/384',
        dropMultiplier5x: '1/153',
        item: 'Venator ring',
        source: 'The Leviathan',
      },
      {
        baseRarity: '1/768',
        dropMultiplier2x: '1/384',
        dropMultiplier5x: '1/153',
        item: 'Soulreaper axe pieces',
        source: 'The Leviathan',
      },
      {
        baseRarity: '1/768',
        dropMultiplier2x: '1/384',
        dropMultiplier5x: '1/153',
        item: 'Virtus robes',
        source: 'The Leviathan',
      },
      {
        baseRarity: '1/53',
        dropMultiplier2x: '1/26',
        dropMultiplier5x: '1/10',
        item: "Awakener's orb",
        source: 'The Leviathan',
      },
      {
        baseRarity: '1/400',
        dropMultiplier2x: '1/200',
        dropMultiplier5x: '1/80',
        item: 'Fish barrel',
        source: 'Tempoross',
      },
      {
        baseRarity: '1/400',
        dropMultiplier2x: '1/200',
        dropMultiplier5x: '1/80',
        item: 'Tackle box',
        source: 'Tempoross',
      },
      {
        baseRarity: '1/1,600',
        dropMultiplier2x: '1/800',
        dropMultiplier5x: '1/320',
        item: 'Tome of water',
        source: 'Tempoross',
      },
      {
        baseRarity: '1/8,000',
        dropMultiplier2x: '1/4,000',
        dropMultiplier5x: '1/1,600',
        item: 'Dragon harpoon',
        source: 'Tempoross',
      },
      {
        baseRarity: '1/300',
        dropMultiplier2x: '1/150',
        dropMultiplier5x: '1/60',
        item: 'Abyssal needle',
        source: 'Guardians of the Rift',
      },
      {
        baseRarity: '1/700',
        dropMultiplier2x: '1/350',
        dropMultiplier5x: '1/140',
        item: 'Abyssal lantern',
        source: 'Guardians of the Rift',
      },
      {
        baseRarity: '1/1,200',
        dropMultiplier2x: '1/600',
        dropMultiplier5x: '1/240',
        item: 'Abyssal dye',
        source: 'Guardians of the Rift',
      },
    ],
    notableSettlements: [
      'Bandit Camp',
      'Necropolis',
      'Ruins of Unkah',
      'Bedabin Camp',
      'Desert Mining Camp',
      'Nardah',
      'Pollnivneach',
      'Ruins of Uzer',
      'Uzer Oasis',
      "Giants' Plateau",
      'Sophanem',
    ],
  },
  fremennik: {
    autoCompletedAchievements: [],
    autoCompletedQuests: ['Secrets of the North', 'Horror from the Deep', 'Dragon Slayer II', 'Mountain Daughter'],
    description:
      'The Fremennik Province area covers the entire Fremennik Province (including the Fremennik Isles) along with Lunar Isle and Weiss. Its southern border is defined by the river south of Rellekka, with the lighthouse included.',
    echoBoss: 'Dagannoth Kings',
    isAccessible: true,
    isStarting: false,
    name: 'Fremennik Province',
    notableActivities: ['Vorkath', 'Dagannoth Kings', 'Duke Sucellus', 'Phantom Muspah'],
    notableDrops: [
      {
        baseRarity: '1/25',
        dropMultiplier2x: 'N/A',
        dropMultiplier5x: 'N/A',
        item: "V's helm",
        source: 'Echo Dagannoth Kings',
      },
      {
        baseRarity: '1/5,000',
        dropMultiplier2x: '1/2,500',
        dropMultiplier5x: '1/1,000',
        item: 'Draconic and Skeletal visage',
        source: 'Vorkath',
      },
      {
        baseRarity: '1/1,000',
        dropMultiplier2x: '1/500',
        dropMultiplier5x: '1/200',
        item: 'Dragonbone necklace',
        source: 'Vorkath',
      },
      {
        baseRarity: '1/128',
        dropMultiplier2x: '1/64',
        dropMultiplier5x: '1/25',
        item: 'Dagannoth King rings',
        source: 'Dagannoth Kings',
      },
      {
        baseRarity: '1/128',
        dropMultiplier2x: '1/64',
        dropMultiplier5x: '1/25',
        item: 'Dagannoth King non-ring unique table items',
        source: 'Dagannoth Kings',
      },
      {
        baseRarity: '1/128',
        dropMultiplier2x: '1/64',
        dropMultiplier5x: '1/25',
        item: 'Dragon Axe',
        source: 'Dagannoth Kings',
      },
      {
        baseRarity: '1/5,000',
        dropMultiplier2x: '1/2,500',
        dropMultiplier5x: '1/1,000',
        item: 'Basilisk jaw',
        source: 'Basilisk Knight',
      },
      {
        baseRarity: '1/384',
        dropMultiplier2x: '1/192',
        dropMultiplier5x: '1/76',
        item: 'Leaf-bladed sword',
        source: 'Kurask',
      },
      {
        baseRarity: '1/500',
        dropMultiplier2x: '1/250',
        dropMultiplier5x: '1/100',
        item: 'Leaf-bladed sword',
        source: 'Turoth',
      },
      {
        baseRarity: '1/1,026',
        dropMultiplier2x: '1/513',
        dropMultiplier5x: '1/205',
        item: 'Leaf-bladed battleaxe',
        source: 'Kurask, King Kurask',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'Brine sabre',
        source: 'Brine rat',
      },
      {
        baseRarity: '1/720',
        dropMultiplier2x: '1/360',
        dropMultiplier5x: '1/144',
        item: 'Magus ring',
        source: 'Duke Sucellus',
      },
      {
        baseRarity: '1/720',
        dropMultiplier2x: '1/360',
        dropMultiplier5x: '1/144',
        item: 'Soulreaper axe pieces',
        source: 'Duke Sucellus',
      },
      {
        baseRarity: '1/720',
        dropMultiplier2x: '1/360',
        dropMultiplier5x: '1/144',
        item: 'Virtus robes',
        source: 'Duke Sucellus',
      },
      {
        baseRarity: '1/48',
        dropMultiplier2x: '1/24',
        dropMultiplier5x: '1/9',
        item: "Awakener's orb",
        source: 'Duke Sucellus',
      },
      {
        baseRarity: '1/25',
        dropMultiplier2x: '1/12',
        dropMultiplier5x: '1/5',
        item: 'Frozen cache',
        source: 'Phantom Muspah',
      },
      {
        baseRarity: '1/50',
        dropMultiplier2x: '1/25',
        dropMultiplier5x: '1/10',
        item: 'Ancient sceptre',
        source: 'Phantom Muspah',
      },
      {
        baseRarity: '1/100',
        dropMultiplier2x: '1/50',
        dropMultiplier5x: '1/20',
        item: 'Venator shard',
        source: 'Phantom Muspah',
      },
    ],
    notableSettlements: [
      'Keldagrim',
      'Ghorrock Dungeon',
      'Miscellania & Etceteria',
      'Neitiznot & Jatizso',
      'Rellekka',
      'Island of Stone',
      'Mountain Camp',
      "Pirates' Cove",
      'Ungael',
      'Waterbirth Island',
      'Weiss',
      'Lunar Isle',
    ],
  },
  general: {
    autoCompletedAchievements: [],
    autoCompletedQuests: [],
    description:
      'General covers miscellaneous areas available to everyone outside of Varlamore and Karamja. This covers areas accessible only via fairy rings.',
    isAccessible: true,
    isStarting: false,
    name: 'General',
    notableActivities: ['Abyssal Sire', 'Fairy rings'],
    notableSettlements: ['Zanaris', 'Abyssal Area', 'Abyssal Nexus', 'Gorak Plane', 'Enchanted Valley'],
  },
  kandarin: {
    autoCompletedAchievements: [],
    autoCompletedQuests: [
      "King's Ransom",
      'Monkey Madness II',
      'Swan Song',
      'Dragon Slayer II',
      'Hand in the Sand',
      'Elemental Workshop II',
      'Freeing Skrach Uglogwee',
    ],
    description:
      'The Kandarin area covers the entire Kingdom of Kandarin, along with the Feldip Hills, Ape Atoll and Crash Island. Access to Nightmare Zone is restricted - points must be purchased for 1 gp each from Dominic Onion.',
    echoBoss: 'Thermonuclear Smoke Devil',
    isAccessible: true,
    isStarting: false,
    name: 'Kandarin',
    notableActivities: ['Kraken', 'Thermonuclear Smoke Devil', 'Demonic Gorillas', 'Fishing Trawler'],
    notableSettlements: [
      'Ardougne',
      'Barbarian Outpost',
      'Catherby',
      'Corsair Cove',
      "Gu'Tanoth",
      "Myths' Guild",
      'Piscatoris Fishing Colony',
      'Port Khazard',
      "Seers' Village",
      'Tree Gnome Stronghold',
      'Tree Gnome Village',
      'Yanille',
      'Ape Atoll',
    ],
  },
  karamja: {
    autoCompletedAchievements: [],
    autoCompletedQuests: ['Shilo Village', 'Jungle Potion'],
    description:
      'The Karamja area covers the entire island of Karamja along with the island of Crandor and the Realm of the Fisher King. Instances of areas in Karamja and underground areas with an entrance in Karamja will also be included.',
    isAccessible: true,
    isStarting: false,
    name: 'Karamja',
    notableActivities: ['TzHaar areas', 'Crandor', 'Realm of the Fisher King'],
    notableDrops: [
      {
        baseRarity: '1/2,000',
        dropMultiplier2x: '1/1,000',
        dropMultiplier5x: '1/400',
        item: 'Obsidian helmet, platebody, and legs',
        source: 'TzHaar-Ket',
      },
      {
        baseRarity: '1/512',
        dropMultiplier2x: '1/256',
        dropMultiplier5x: '1/102',
        item: 'TzHaar weaponry',
        source: 'TzHaar-Ket and TzHaar-Xil',
      },
      {
        baseRarity: '1/4,096',
        dropMultiplier2x: '1/2,048',
        dropMultiplier5x: '1/819',
        item: 'Toktz-mej-tal',
        source: 'TzHaar-Mej',
      },
      {
        baseRarity: '1/682',
        dropMultiplier2x: '1/341',
        dropMultiplier5x: '1/136',
        item: 'Toktz-xil-ak and Toktz-xil-ek',
        source: 'TzHaar-Xil',
      },
      {
        baseRarity: '1/10,000',
        dropMultiplier2x: '1/5,000',
        dropMultiplier5x: '1/2,000',
        item: 'Draconic visage',
        source: 'Steel and Iron dragons',
      },
      {
        baseRarity: '1/100',
        dropMultiplier2x: '1/50',
        dropMultiplier5x: '1/20',
        item: 'Gout tuber',
        source: 'Tai Bwo Wannai Cleanup',
      },
    ],
    notableSettlements: ['Brimhaven', 'Ship Yard', 'Musa Point', 'Shilo Village', 'Tai Bwo Wannai', 'Mor Ul Rek'],
    unlocksAfterTasks: 80,
  },
  kourend: {
    autoCompletedAchievements: [],
    autoCompletedQuests: ['A Kingdom Divided'],
    description:
      'The Kebos and Kourend area covers the entirety of Kebos and Kourend. Instances of areas in Kebos and Kourend and underground areas with an entrance in Kebos and Kourend will also be included.',
    echoBoss: 'Hespori',
    isAccessible: true,
    isStarting: false,
    name: 'Kebos and Kourend',
    notableActivities: [
      'Chambers of Xeric',
      'Mount Karuulm Slayer Dungeon',
      'Catacombs of Kourend',
      'Sarachnis',
      'Woodcutting and Farming Guild',
      'Tithe Farm',
      'Wintertodt',
      'Soul and Blood Altar',
      'Arceuus Library',
    ],
    notableSettlements: [],
  },
  misthalin: {
    autoCompletedAchievements: [],
    autoCompletedQuests: [],
    description: 'Misthalin is not accessible in the Demonic Pacts League.',
    isAccessible: false,
    isStarting: false,
    name: 'Misthalin',
    notableActivities: [],
    notableSettlements: [],
  },
  morytania: {
    autoCompletedAchievements: [],
    autoCompletedQuests: ['A Taste of Hope', 'The Great Brain Robbery', 'Ghosts Ahoy', 'Vampyre Slayer'],
    description:
      "The Morytania area covers the entirety of Morytania along with the island of Mos Le'Harmless, Braindeath Island, Dragontooth Island and Harmony Island.",
    echoBoss: 'Grotesque Guardians',
    isAccessible: true,
    isStarting: false,
    name: 'Morytania',
    notableActivities: ['Barrows', 'Theatre of Blood', 'The Nightmare', "Phosani's Nightmare", 'Araxxor'],
    notableSettlements: [
      'Burgh de Rott',
      "Mos Le'Harmless",
      'Canifis',
      'Darkmeyer',
      'Meiyerditch',
      "Mort'ton",
      'Port Phasmatys',
      'Slepe',
      'Ver Sinhaza',
    ],
  },
  tirannwn: {
    autoCompletedAchievements: [],
    autoCompletedQuests: ['Song of the Elves'],
    description:
      'The Tirannwn area covers the entirety of Tirannwn along with the Temple of Light and the Underground Pass.',
    echoBoss: 'Corrupted Hunllef',
    isAccessible: true,
    isStarting: false,
    name: 'Tirannwn',
    notableActivities: [
      'The Gauntlet',
      'The Corrupted Gauntlet',
      'Zulrah',
      'Zalcano',
      'Crystal Implings',
      'Prifddinas Agility Course',
      'Death Altar',
    ],
    notableSettlements: ['Prifddinas'],
  },
  varlamore: {
    autoCompletedAchievements: ['Back to Our Roots', 'Demonic Rebound', 'Grub Patrol', 'Perfect Doom'],
    autoCompletedQuests: ['Children of the Sun', "Twilight's Promise"],
    description:
      'Varlamore covers the entirety of Varlamore, including the island of Aldarin and the Stranglewood. As the starting region, many quests are automatically unlocked when beginning the league.',
    echoBoss: 'Amoxliatl',
    isAccessible: true,
    isStarting: true,
    name: 'Varlamore',
    notableActivities: [
      'Fortis Colosseum',
      'Moons of Peril',
      'Vardorvis',
      'Hunter Guild',
      'Colossal Wyrm Agility Course',
      'Wealthy citizen thieving',
      'Amoxliatl',
      'Hueycoatl',
      'Mastering Mixology',
      'Vale Totems',
      'Doom of Mokhaiotl',
    ],
    notableDrops: [
      {
        baseRarity: '1/30',
        category: 'General',
        dropMultiplier2x: 'N/A',
        dropMultiplier5x: 'N/A',
        item: 'Infernal tecpatl',
        source: 'Echo Amoxliatl',
      },
      {
        baseRarity: '1/56',
        category: 'General',
        dropMultiplier2x: '1/28',
        dropMultiplier5x: '1/11',
        item: 'Any unique reward',
        source: 'Moons of Peril',
      },
      {
        baseRarity: '1/224',
        category: 'General',
        dropMultiplier2x: '1/112',
        dropMultiplier5x: '1/44',
        item: 'Any individual unique',
        source: 'Moons of Peril',
      },
      {
        baseRarity: '1/100',
        category: 'General',
        dropMultiplier2x: '1/50',
        dropMultiplier5x: '1/20',
        item: 'Glacial temotli',
        source: 'Amoxliatl',
      },
      {
        baseRarity: '1/25',
        category: 'General',
        dropMultiplier2x: '1/12',
        dropMultiplier5x: '1/5',
        item: 'Pendant of ates',
        source: 'Amoxliatl',
      },
      {
        baseRarity: '1/500',
        category: 'General',
        dropMultiplier2x: '1/250',
        dropMultiplier5x: '1/100',
        item: 'Glacial temotli',
        source: 'Frost nagua',
      },
      {
        baseRarity: '1/100',
        category: 'General',
        dropMultiplier2x: '1/50',
        dropMultiplier5x: '1/20',
        item: 'Pendant of ates',
        source: 'Frost nagua',
      },
      {
        baseRarity: '1/400',
        category: 'General',
        dropMultiplier2x: '1/200',
        dropMultiplier5x: '1/80',
        item: 'Earthbound tecpatl',
        source: 'Earthen nagua',
      },
      {
        baseRarity: '1/450',
        category: 'General',
        dropMultiplier2x: '1/225',
        dropMultiplier5x: '1/90',
        item: 'Sulphur blades',
        source: 'Sulphur nagua',
      },
      {
        baseRarity: '1/28',
        category: 'General',
        dropMultiplier2x: '1/14',
        dropMultiplier5x: '1/5',
        item: 'Hueycoatl hide',
        source: 'Hueycoatl',
      },
      {
        baseRarity: '1/90',
        category: 'General',
        dropMultiplier2x: '1/45',
        dropMultiplier5x: '1/18',
        item: 'Tome of earth',
        source: 'Hueycoatl',
      },
      {
        baseRarity: '1/105',
        category: 'General',
        dropMultiplier2x: '1/52',
        dropMultiplier5x: '1/21',
        item: 'Dragon hunter wand',
        source: 'Hueycoatl',
      },
      {
        baseRarity: '1/75',
        category: 'General',
        dropMultiplier2x: '1/37',
        dropMultiplier5x: '1/15',
        item: 'Tooth half of key',
        source: 'Hueycoatl',
      },
      {
        baseRarity: '1/1,088',
        category: 'General',
        dropMultiplier2x: '1/544',
        dropMultiplier5x: '1/217',
        item: 'Soulreaper axe pieces',
        source: 'Vardorvis',
      },
      {
        baseRarity: '1/1,088',
        category: 'General',
        dropMultiplier2x: '1/544',
        dropMultiplier5x: '1/217',
        item: 'Ultor ring',
        source: 'Vardorvis',
      },
      {
        baseRarity: '1/1,088',
        category: 'General',
        dropMultiplier2x: '1/544',
        dropMultiplier5x: '1/217',
        item: 'Virtus robes',
        source: 'Vardorvis',
      },
      {
        baseRarity: '1/80',
        category: 'General',
        dropMultiplier2x: '1/40',
        dropMultiplier5x: '1/16',
        item: "Awakener's orb",
        source: 'Vardorvis',
      },
      {
        baseRarity: '1/50',
        category: 'General',
        dropMultiplier2x: '1/25',
        dropMultiplier5x: '1/10',
        item: "Hunters' Guild loot sack rares",
        source: 'Hunter rumours',
      },
      {
        baseRarity: '1/1,000',
        category: 'General',
        dropMultiplier2x: '1/500',
        dropMultiplier5x: '1/200',
        item: 'Tecu salamander',
        source: 'Hunting',
      },
      {
        baseRarity: '1/200',
        category: 'General',
        dropMultiplier2x: '1/100',
        dropMultiplier5x: '1/40',
        item: 'Bow string spool',
        source: 'Vale offerings',
      },
      {
        baseRarity: '1/333',
        category: 'General',
        dropMultiplier2x: '1/166',
        dropMultiplier5x: '1/66',
        item: 'Fletching knife',
        source: 'Vale offerings',
      },
      {
        baseRarity: '1/500',
        category: 'General',
        dropMultiplier2x: '1/250',
        dropMultiplier5x: '1/100',
        item: 'Greenman mask',
        source: 'Vale offerings',
      },
      {
        baseRarity: '1/650',
        category: 'General',
        dropMultiplier2x: '1/325',
        dropMultiplier5x: '1/130',
        item: 'Antler guard',
        source: 'Elder custodian stalker',
      },
      {
        baseRarity: '1/650',
        category: 'General',
        dropMultiplier2x: '1/325',
        dropMultiplier5x: '1/130',
        item: 'Antler guard',
        source: 'Ancient Custodian',
      },
      {
        baseRarity: '1/800',
        category: 'General',
        dropMultiplier2x: '1/400',
        dropMultiplier5x: '1/160',
        item: 'Antler guard',
        source: 'Mature custodian stalker',
      },
      {
        baseRarity: '1/10,000',
        category: 'General',
        dropMultiplier2x: '1/5,000',
        dropMultiplier5x: '1/2,000',
        item: 'Draconic visage',
        source: 'Brutal blue dragon',
      },
      {
        baseRarity: '~2/25',
        category: 'Fortis Colosseum',
        dropMultiplier2x: '~7/45',
        dropMultiplier5x: '~6/17',
        item: 'Echo boots',
        source: 'Fortis Colosseum',
      },
      {
        baseRarity: '~5/42',
        category: 'Fortis Colosseum',
        dropMultiplier2x: '~7/31',
        dropMultiplier5x: '~20/41',
        item: 'Sunfire fanatic armour',
        source: 'Fortis Colosseum',
      },
      {
        baseRarity: '~1/84',
        category: 'Fortis Colosseum',
        dropMultiplier2x: '~1/42',
        dropMultiplier5x: '~1/17',
        item: 'Tonalztics of ralos',
        source: 'Fortis Colosseum',
      },
      {
        baseRarity: '~1/111',
        category: 'Doom of Mokhaiotl',
        dropMultiplier2x: '~1/55',
        dropMultiplier5x: '~1/22',
        item: 'Confliction gauntlets',
        source: 'Doom of Mokhaiotl',
      },
      {
        baseRarity: '~1/116',
        category: 'Doom of Mokhaiotl',
        dropMultiplier2x: '~1/58',
        dropMultiplier5x: '~1/23',
        item: 'Eye of ayak',
        source: 'Doom of Mokhaiotl',
      },
      {
        baseRarity: '~1/123',
        category: 'Doom of Mokhaiotl',
        dropMultiplier2x: '~1/62',
        dropMultiplier5x: '~1/25',
        item: 'Avernic treads',
        source: 'Doom of Mokhaiotl',
      },
    ],
    notableSettlements: ['Civitas illa Fortis', 'Aldarin', 'Cam Torum', 'Tal Teklan', 'Auburnvale'],
  },
  wilderness: {
    autoCompletedAchievements: [],
    autoCompletedQuests: ['Enter the Abyss'],
    description:
      'The Wilderness area covers the entirety of the Wilderness. As Misthalin is not accessible in this league, the Edgeville Dungeon will also be inaccessible. Last Man Standing and Bounty Hunter will not be active.',
    echoBoss: 'King Black Dragon',
    isAccessible: true,
    isStarting: false,
    name: 'Wilderness',
    notableActivities: [
      'Revenants',
      'Chaos Fanatic',
      'Crazy Archaeologist',
      'Scorpia',
      'King Black Dragon',
      'Corporeal Beast',
    ],
    notableSettlements: [
      'Bandit Camp',
      "Dark Warriors' Fortress",
      'Ferox Enclave',
      'Mage Arena',
      "Rogues' Castle",
      "Pirates' Hideout",
    ],
  },
};

export const DemonicPactsLeagueRegions: Record<string, LeagueRegion> = {
  asgarnia: {
    name: 'Asgarnia',
    wikiUrl: 'https://runescape.wiki/w/Asgarnia',
  },
  desert: {
    name: 'Kharidian Desert',
    wikiUrl: 'https://runescape.wiki/w/Kharidian_Desert',
  },
  fremennik: {
    name: 'Fremennik Province',
    wikiUrl: 'https://runescape.wiki/w/Fremennik_Province',
  },
  general: {
    name: 'General',
    wikiUrl: '',
  },
  kandarin: {
    name: 'Kandarin',
    wikiUrl: 'https://runescape.wiki/w/Kandarin',
  },
  karamja: {
    name: 'Karamja',
    wikiUrl: 'https://runescape.wiki/w/Karamja',
  },
  kourend: {
    name: 'Kebos and Kourend',
    wikiUrl: 'https://runescape.wiki/w/Kebos_and_Kourend',
  },
  misthalin: {
    name: 'Misthalin',
    wikiUrl: 'https://runescape.wiki/w/Misthalin',
  },
  morytania: {
    name: 'Morytania',
    wikiUrl: 'https://runescape.wiki/w/Morytania',
  },
  tirannwn: {
    name: 'Tirannwn',
    wikiUrl: 'https://runescape.wiki/w/Tirannwn',
  },
  varlamore: {
    name: 'Varlamore',
    wikiUrl: 'https://runescape.wiki/w/Varlamore',
  },
  wilderness: {
    name: 'Wilderness',
    wikiUrl: 'https://runescape.wiki/w/Wilderness',
  },
};
