import { Item } from '../Item';

const amuletOfMagicData = {
  id: 1478,
  name: 'Amulet of magic',
  iconUrl: '/assets/items/amulet-of-magic.png',
  examine: 'A mystical amulet.',
  value: 315,
  highAlch: 189,
  lowAlch: 126,
  weight: 0.01,
  members: false,
  tradeable: true,
  equipable: true,
  releaseDate: '2001-12-10',
  destroy: 'Drop',
  questItem: false,
  stackable: false,
  noted: false,
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Amulet_of_magic',
  attackStab: 0,
  attackSlash: 0,
  attackCrush: 0,
  attackRanged: 0,
  attackMagic: 8,
  defenceStab: 0,
  defenceSlash: 0,
  defenceCrush: 0,
  defenceRanged: 0,
  defenceMagic: 0,
  strength: 0,
  rangedStrength: 0,
  magicDamage: 0,
  prayer: 0,
};

export const AmuletOfMagic = Item.fromJson(amuletOfMagicData);
