import { Item } from "../Item";

const ClueScrollHardTheMagicOf4ColoursAnEarlyExperienceYouCouldLearnData = {
  id: 19857,
  name: "Clue scroll (hard) - The magic of 4 colours, an early experience you could learn",
  examine: "",
  value: 0,
  highAlch: 0,
  lowAlch: 0,
  weight: 0,
  members: false,
  tradeable: false,
  equipable: false,
  releaseDate: "",
  destroy: "Drop",
  questItem: false,
  stackable: false,
  noted: false,
  officialWikiUrl: "",
  iconUrl: "",
  attackStab: 0,
  attackSlash: 0,
  attackCrush: 0,
  attackMagic: 0,
  attackRanged: 0,
  defenceStab: 0,
  defenceSlash: 0,
  defenceCrush: 0,
  defenceMagic: 0,
  defenceRanged: 0,
  meleeStrength: 0,
  rangedStrength: 0,
  magicDamage: 0,
  prayer: 0
};
export const ClueScrollHardTheMagicOf4ColoursAnEarlyExperienceYouCouldLearn = Item.fromJson(ClueScrollHardTheMagicOf4ColoursAnEarlyExperienceYouCouldLearnData);
