import { Item } from "../Item";

const ClueScrollEasyBehindLumbridgeCastleData = {
    examine: "",
    value: 0,
    highAlch: 0,
    lowAlch: 0,
    weight: 0,
    members: false,
    tradeable: false,
    equipable: false,
    releaseDate: "",
    destroy: "Drop",
    questItem: false,
    stackable: false,
    noted: false,
    officialWikiUrl: "",
    name: "Clue scroll (easy) - Behind Lumbridge Castle",
    attackStab: 0,
    attackSlash: 0,
    attackCrush: 0,
    attackMagic: 0,
    attackRanged: 0,
    defenceStab: 0,
    defenceSlash: 0,
    defenceCrush: 0,
    defenceMagic: 0,
    defenceRanged: 0,
    id: 28058,
    iconUrl: "",
    meleeStrength: 0,
    rangedStrength: 0,
    magicDamage: 0,
    prayer: 0
};
export const ClueScrollEasyBehindLumbridgeCastle = Item.fromJson(ClueScrollEasyBehindLumbridgeCastleData);
