import { Item } from "../Item";

const ClueScrollEliteYouMustBe100ToPlayWithMeData = {
  id: 19811,
  name: "Clue scroll (elite) - You must be 100 to play with me",
  examine: "",
  value: 0,
  highAlch: 0,
  lowAlch: 0,
  weight: 0,
  members: false,
  tradeable: false,
  equipable: false,
  releaseDate: "",
  destroy: "Drop",
  questItem: false,
  stackable: false,
  noted: false,
  officialWikiUrl: "",
  iconUrl: "",
  attackStab: 0,
  attackSlash: 0,
  attackCrush: 0,
  attackMagic: 0,
  attackRanged: 0,
  defenceStab: 0,
  defenceSlash: 0,
  defenceCrush: 0,
  defenceMagic: 0,
  defenceRanged: 0,
  meleeStrength: 0,
  rangedStrength: 0,
  magicDamage: 0,
  prayer: 0
};
export const ClueScrollEliteYouMustBe100ToPlayWithMe = Item.fromJson(ClueScrollEliteYouMustBe100ToPlayWithMeData);
