import { Item } from "../Item";

const OrangePumpkin2024HalloweenEventuncarvedData = {
  id: 30165,
  name: "Orange pumpkin (2024 Halloween event)#Uncarved",
  examine: "",
  value: 0,
  highAlch: 0,
  lowAlch: 0,
  weight: 0,
  members: false,
  tradeable: false,
  equipable: false,
  releaseDate: "",
  destroy: "Drop",
  questItem: false,
  stackable: false,
  noted: false,
  officialWikiUrl: "",
  iconUrl: "",
  attackStab: 0,
  attackSlash: 0,
  attackCrush: 0,
  attackMagic: 0,
  attackRanged: 0,
  defenceStab: 0,
  defenceSlash: 0,
  defenceCrush: 0,
  defenceMagic: 0,
  defenceRanged: 0,
  meleeStrength: 0,
  rangedStrength: 0,
  magicDamage: 0,
  prayer: 0
};
export const OrangePumpkin2024HalloweenEventuncarved = Item.fromJson(OrangePumpkin2024HalloweenEventuncarvedData);
