import { Item, ItemJson } from '../Item';
const waterRuneData: ItemJson = {
  equipable: false,
  examine: 'One of the four basic elemental runes.',
  id: 555,
  members: false,
  name: 'Water rune',
  iconUrl: '/assets/items/555.png',
  noted: false,
  officialWikiUrl: 'https://oldschool.runescape.wiki/w/Water_rune',
  questItem: false,
  stackable: true,
  tradeable: true,
  value: 17,
  weight: 0.002,
  highAlch: 0,
  lowAlch: 0,
  releaseDate: '',
  destroy: '',
  attackStab: 0,
  attackSlash: 0,
  attackCrush: 0,
  attackMagic: 0,
  attackRanged: 0,
  defenceStab: 0,
  defenceSlash: 0,
  defenceCrush: 0,
  defenceMagic: 0,
  defenceRanged: 0,
  meleeStrength: 0,
  rangedStrength: 0,
  magicDamage: 0,
  prayer: 0
};

export const WaterRune = Item.fromJson(waterRuneData);
