import { Quest } from '../Quest';
import { QuestRequirement, LevelRequirement } from '../../Requirement';
import { QuestDifficulty, QuestLength, QuestStatus } from '../enums';
const AKingdomDivided: Quest = {
  id: 0,
  name: 'A Kingdom Divided',
  members: true,
  difficulty: QuestDifficulty.Master,
  length: QuestLength.Long,
  requirements: [
    new QuestRequirement('Client of Kourend'),
    new QuestRequirement('The Depths of Despair'),
    new QuestRequirement('The Queen of Thieves'),
    new QuestRequirement('The Ascent of Arceuus'),
    new QuestRequirement('The Forsaken Tower'),
    new LevelRequirement('Thieving', 54, false),
    new LevelRequirement('Agility', 52, false),
    new LevelRequirement('Woodcutting', 52, false),
    new LevelRequirement('Magic', 50, false),
    new LevelRequirement('Mining', 42, false),
    new LevelRequirement('Smithing', 42, false),
    new LevelRequirement('Farming', 35, false),
    new LevelRequirement('Crafting', 38, false),
    new LevelRequirement('Hunter', 42, false),
    new LevelRequirement('Herblore', 45, false),
  ],
  questPoints: 2,
  startLocation: '',
  description: '',
  steps: [],
  status: QuestStatus.NotStarted,
  miniquest: false,
  shortName: 'aKingdomDivided',
  url: 'https://oldschool.runescape.wiki/w/A_Kingdom_Divided',
  series: 'Great Kourend',
  age: '',

  recommendations: [
    { type: 'tip', name: 'Combat level 70+', note: 'Recommended for boss fights' },
    { type: 'tip', name: '43+ Prayer', note: 'Protect from Magic, Missiles, Melee' },
    { type: 'item', name: 'Stamina or energy potions' },
    { type: 'item', name: 'Antipoison' },
    { type: 'item', name: "Kharedst's memoirs" },
    { type: 'item', name: "Xeric's talisman" },
    { type: 'item', name: 'Games necklace' },
    { type: 'item', name: 'Skills necklace' },
    { type: 'item', name: "Rada's blessing", note: '1+ recommended' },
    { type: 'travel', name: 'Access to fairy rings' },
    { type: 'item', name: 'Food and combat equipment', note: 'For high-level fights' },
    { type: 'item', name: 'Axe' },
    { type: 'item', name: 'Runes', note: 'To cast Fire Bolt or better' },
    { type: 'item', name: 'Defence potion', quantity: 3, note: '3+ doses' },
    { type: 'item', name: 'Volcanic sulphur' },
    { type: 'item', name: 'Molten glass' },
    { type: 'item', name: 'Dark essence block', alternatives: ['Pickaxe', 'Chisel'] },
  ],
  recommendedSkills: {
    Hitpoints: 70,
    Prayer: 43,
    Combat: 70,
  },
  recommendedPrayers: ['Protect from Magic', 'Protect from Missiles', 'Protect from Melee'],
  rewards: {
    experience: [],
    questPoints: 2,
    items: [{ name: 'Book of the dead', quantity: 1 }],
    areas: ['Ability to set respawn point to Kourend Castle'],
    unlocks: [
      {
        description: '24 new spells in the Arceuus spellbook',
        url: 'https://oldschool.runescape.wiki/w/Arceuus_spellbook',
      },
      { description: 'Ability to fight Yama', url: 'https://oldschool.runescape.wiki/w/Yama' },
    ],
    lamps: [
      {
        amount: 10000,
        skillRestriction: 'Any skill level 40 or above',
        note: 'Two lamps are awarded',
      },
    ],
    points: [],
    pets: [],
  },
};

export default AKingdomDivided;
