import { LevelRequirement, QuestRequirement } from '../../Requirement';
import { QuestDifficulty, QuestLength, QuestStatus } from '../enums';
import { Quest } from '../Quest';
const AKingdomDivided: Quest = {
  description: '',
  difficulty: QuestDifficulty.Master,
  id: 0,
  length: QuestLength.Long,
  members: true,
  miniquest: false,
  age: '',
  name: 'A Kingdom Divided',
  questPoints: 2,
  recommendations: [
    { name: 'Combat level 70+', note: 'Recommended for boss fights', type: 'tip' },
    { name: '43+ Prayer', note: 'Protect from Magic, Missiles, Melee', type: 'tip' },
    { name: 'Stamina or energy potions', type: 'item' },
    { name: 'Antipoison', type: 'item' },
    { name: "Kharedst's memoirs", type: 'item' },
    { name: "Xeric's talisman", type: 'item' },
    { name: 'Games necklace', type: 'item' },
    { name: 'Skills necklace', type: 'item' },
    { name: "Rada's blessing", note: '1+ recommended', type: 'item' },
    { name: 'Access to fairy rings', type: 'travel' },
    { name: 'Food and combat equipment', note: 'For high-level fights', type: 'item' },
    { name: 'Axe', type: 'item' },
    { name: 'Runes', note: 'To cast Fire Bolt or better', type: 'item' },
    { name: 'Defence potion', note: '3+ doses', quantity: 3, type: 'item' },
    { name: 'Volcanic sulphur', type: 'item' },
    { name: 'Molten glass', type: 'item' },
    { alternatives: ['Pickaxe', 'Chisel'], name: 'Dark essence block', type: 'item' },
  ],
  recommendedPrayers: ['Protect from Magic', 'Protect from Missiles', 'Protect from Melee'],
  requirements: [
    new QuestRequirement('Client of Kourend'),
    new QuestRequirement('The Depths of Despair'),
    new QuestRequirement('The Queen of Thieves'),
    new QuestRequirement('The Ascent of Arceuus'),
    new QuestRequirement('The Forsaken Tower'),
    new LevelRequirement('Thieving', 54, false),
    new LevelRequirement('Agility', 52, false),
    new LevelRequirement('Woodcutting', 52, false),
    new LevelRequirement('Magic', 50, false),
    new LevelRequirement('Mining', 42, false),
    new LevelRequirement('Smithing', 42, false),
    new LevelRequirement('Farming', 35, false),
    new LevelRequirement('Crafting', 38, false),
    new LevelRequirement('Hunter', 42, false),
    new LevelRequirement('Herblore', 45, false),
  ],
  recommendedSkills: {
    Combat: 70,
    Hitpoints: 70,
    Prayer: 43,
  },
  series: 'Great Kourend',
  rewards: {
    areas: ['Ability to set respawn point to Kourend Castle'],
    experience: [],
    items: [{ name: 'Book of the dead', quantity: 1 }],
    lamps: [
      {
        amount: 10000,
        note: 'Two lamps are awarded',
        skillRestriction: 'Any skill level 40 or above',
      },
    ],
    pets: [],
    points: [],
    questPoints: 2,
    unlocks: [
      {
        description: '24 new spells in the Arceuus spellbook',
        url: 'https://oldschool.runescape.wiki/w/Arceuus_spellbook',
      },
      { description: 'Ability to fight Yama', url: 'https://oldschool.runescape.wiki/w/Yama' },
    ],
  },
  startLocation: '',
  shortName: 'aKingdomDivided',
  status: QuestStatus.NotStarted,
  steps: [],
  url: 'https://oldschool.runescape.wiki/w/A_Kingdom_Divided',
};

export default AKingdomDivided;
