import { QuestRequirement } from '../../Requirement';
import { QuestDifficulty, QuestLength } from '../enums';
import { Quest, QuestStatus } from '../Quest';
const RecipeForDisaster: Quest = {
  age: '',
  description: '',
  difficulty: QuestDifficulty.Master,
  id: 0,
  length: QuestLength.VeryLong,
  members: true,
  miniquest: false,
  name: 'Recipe for Disaster',
  questPoints: 10,
  recommendations: [],
  recommendedPrayers: [],
  recommendedSkills: {},
  requirements: [
    new QuestRequirement("Cook's Assistant"),
    new QuestRequirement('Fishing Contest'),
    new QuestRequirement('Goblin Diplomacy'),
    new QuestRequirement('Big Chompy Bird Hunting'),
    new QuestRequirement('Murder Mystery'),
    new QuestRequirement('Nature Spirit'),
    new QuestRequirement("Gertrude's Cat"),
    new QuestRequirement('Shadow of the Storm'),
    new QuestRequirement('The Golem'),
    new QuestRequirement('Demon Slayer'),
    new QuestRequirement('Temple of Ikov'),
    new QuestRequirement('The Tourist Trap'),
    new QuestRequirement('Troll Romance'),
    new QuestRequirement('Desert Treasure'),
    new QuestRequirement('Horror from the Deep'),
    new QuestRequirement("Witch's House"),
    new QuestRequirement('Lost City'),
    new QuestRequirement('Monkey Madness'),
    new QuestRequirement('Shilo Village'),
    new QuestRequirement('Underground Pass'),
    new QuestRequirement('Waterfall Quest'),
  ],
  rewards: {
    areas: [],
    experience: [],
    items: [],
    lamps: [],
    pets: [],
    points: [],
    questPoints: 1,
    unlocks: [],
  },
  series: null,
  shortName: 'recipeForDisaster',
  startLocation: '',
  status: QuestStatus.NotStarted,
  steps: [],
  url: 'https://oldschool.runescape.wiki/w/Recipe_for_Disaster',
};

export default RecipeForDisaster;
