import { Skill } from '../../account/Skill';
import { LevelRequirement, QuestRequirement } from '../../Requirement';
import { QuestDifficulty, QuestLength } from '../enums';
import { Quest, QuestStatus } from '../Quest';

const TheFinalDawn: Quest = {
  age: 'New',
  description: `The Final Dawn is a Grandmaster quest released in 2024. It is the epic conclusion to the Mahjarrat storyline, featuring challenging puzzles, high-level combat, and significant lore revelations.`,
  difficulty: QuestDifficulty.Grandmaster,
  id: 171,
  length: QuestLength.Long,
  members: true,
  miniquest: false,
  name: 'The Final Dawn',
  questPoints: 4,
  recommendations: [],
  recommendedPrayers: [],
  recommendedSkills: {},
  requirements: [
    new QuestRequirement('The Path of Glouphrie'),
    new QuestRequirement('Song of the Elves'),
    new QuestRequirement("Mourning's End Part II"),
    new QuestRequirement('Sins of the Father'),
    new QuestRequirement('Sins of the Father'),
    new QuestRequirement('Desert Treasure II - The Fallen Empire'),
    new QuestRequirement('Sins of the Father'),
    new LevelRequirement(Skill.Agility, 85, false),
    new LevelRequirement(Skill.Thieving, 85, false),
    new LevelRequirement(Skill.Crafting, 85, false),
    new LevelRequirement(Skill.Magic, 85, false),
    new LevelRequirement(Skill.Smithing, 85, false),
    new LevelRequirement(Skill.Herblore, 85, false),
    new LevelRequirement(Skill.Slayer, 85, false),
    new LevelRequirement(Skill.Mining, 85, false),
    new LevelRequirement(Skill.Firemaking, 85, false),
    new LevelRequirement(Skill.Woodcutting, 85, false),
    new LevelRequirement(Skill.Fishing, 85, false),
    new LevelRequirement(Skill.Cooking, 85, false),
    new LevelRequirement(Skill.Farming, 85, false),
    new LevelRequirement(Skill.Construction, 85, false),
    new LevelRequirement(Skill.Hunter, 85, false),
    new LevelRequirement(Skill.Runecraft, 85, false),
    new LevelRequirement(Skill.Prayer, 85, false),
    new LevelRequirement(Skill.Fletching, 85, false),
    new LevelRequirement(Skill.Ranged, 85, false),
    new LevelRequirement(Skill.Attack, 85, false),
    new LevelRequirement(Skill.Strength, 85, false),
    new LevelRequirement(Skill.Defence, 85, false),
    new LevelRequirement(Skill.Hitpoints, 85, false),
  ],
  rewards: {
    misc: [
      'Access to new areas',
      'Unique quest items',
      'Large experience rewards in multiple skills',
      'New boss encounters',
      'Unlocks new music tracks',
    ],
    questPoints: 4,
  },
  series: 'Mahjarrat',
  shortName: 'theFinalDawn',
  startLocation: 'To be determined',
  status: QuestStatus.NotStarted,
  steps: [],
  url: 'https://oldschool.runescape.wiki/w/The_Final_Dawn',
};

export default TheFinalDawn;
