import {
  CombatLevelRequirement,
  SlayerLevelRequirement,
  QuestRequirement
} from "../../Requirement";
import { Task } from "../Task";

const duradelTasks: Task[] = [
  new Task(
    "Aberrant spectres",
    60,
    200,
    [new SlayerLevelRequirement(60), new CombatLevelRequirement(85)],
    null,
    null,
    ["Deviant spectres"],
    8,
    [],
    0,
    ["Slayer Tower (CKS)"]
  ),
  new Task(
    "Abyssal demons",
    85,
    200,
    [new SlayerLevelRequirement(85), new CombatLevelRequirement(85), new QuestRequirement("Priest in Peril"), new QuestRequirement("Fairytale II - Cure a Queen")],
    null,
    null,
    ["Abyssal Sire"],
    5,
    [],
    0,
    ["Slayer Tower (CKS)"]
  ),
  new Task(
    "Ankou",
    1,
    60,
    [new CombatLevelRequirement(40)],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Stronghold of Security", "Catacombs of Kourend"]
  ),
  new Task(
    "Aviansie",
    1,
    60,
    [new CombatLevelRequirement(70), new QuestRequirement("Death Plateau")],
    null,
    null,
    [],
    8,
    [],
    0,
    ["God Wars Dungeon"]
  ),
  new Task(
    "Black demons",
    1,
    60,
    [new CombatLevelRequirement(80)],
    null,
    null,
    ["Demonic gorilla"],
    8,
    [],
    0,
    ["Taverley Dungeon", "Catacombs of Kourend"]
  ),
  new Task(
    "Black dragons",
    1,
    60,
    [new CombatLevelRequirement(80)],
    null,
    null,
    ["King Black Dragon", "Baby black dragon"],
    8,
    [],
    0,
    ["Taverley Dungeon", "Wilderness"]
  ),
  new Task(
    "Bloodveld",
    50,
    200,
    [new SlayerLevelRequirement(50), new CombatLevelRequirement(50)],
    null,
    null,
    ["Mutated Bloodveld"],
    8,
    [],
    0,
    ["Meiyerditch Laboratories", "Catacombs of Kourend"]
  ),
  new Task(
    "Blue dragons",
    1,
    60,
    [new CombatLevelRequirement(65)],
    null,
    null,
    ["Baby blue dragon", "Vorkath"],
    8,
    [],
    0,
    ["Taverley Dungeon", "Myth's Guild"]
  ),
  new Task(
    "Cave kraken",
    87,
    200,
    [new SlayerLevelRequirement(87)],
    null,
    null,
    ["Kraken"],
    8,
    [],
    0,
    ["Kraken Cove"]
  ),
  new Task(
    "Cave horrors",
    58,
    200,
    [new SlayerLevelRequirement(58), new CombatLevelRequirement(40), new QuestRequirement("Cabin Fever")],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Mos Le'Harmless Caves"]
  ),
  new Task(
    "Dagannoth",
    1,
    60,
    [new CombatLevelRequirement(75)],
    null,
    null,
    ["Dagannoth Prime", "Dagannoth Rex", "Dagannoth Supreme"],
    8,
    [],
    0,
    ["Lighthouse", "Catacombs of Kourend"]
  ),
  new Task(
    "Dark beasts",
    90,
    200,
    [new SlayerLevelRequirement(90), new QuestRequirement("Mourning's End Part II")],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Mourner Tunnels"]
  ),
  new Task(
    "Dust devils",
    65,
    200,
    [new SlayerLevelRequirement(65), new QuestRequirement("Desert Treasure")],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Smoke Dungeon", "Catacombs of Kourend"]
  ),
  new Task(
    "Fire giants",
    1,
    60,
    [new CombatLevelRequirement(65)],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Waterfall Dungeon", "Brimhaven Dungeon"]
  ),
  new Task(
    "Gargoyles",
    75,
    200,
    [new SlayerLevelRequirement(75), new CombatLevelRequirement(80)],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Slayer Tower (CKS)"]
  ),
  new Task(
    "Greater demons",
    1,
    60,
    [new CombatLevelRequirement(65)],
    null,
    null,
    ["Skotizo", "Demonic gorilla"],
    8,
    [],
    0,
    ["Brimhaven Dungeon", "Catacombs of Kourend"]
  ),
  new Task(
    "Hellhounds",
    1,
    60,
    [new CombatLevelRequirement(75)],
    null,
    null,
    ["Cerberus"],
    8,
    [],
    0,
    ["Taverley Dungeon", "Wilderness"]
  ),
  new Task(
    "Iron dragons",
    1,
    60,
    [new CombatLevelRequirement(80)],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Brimhaven Dungeon", "Catacombs of Kourend"]
  ),
  new Task(
    "Kalphite",
    1,
    60,
    [new CombatLevelRequirement(15)],
    null,
    null,
    ["Kalphite worker", "Kalphite soldier", "Kalphite guardian", "Kalphite Queen"],
    6,
    [],
    0,
    ["Kalphite Cave"]
  ),
  new Task(
    "Kurask",
    70,
    200,
    [new SlayerLevelRequirement(70), new CombatLevelRequirement(80)],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Fremennik Slayer Dungeon (AJR)"]
  ),
  new Task(
    "Nechryael",
    80,
    200,
    [new SlayerLevelRequirement(80), new CombatLevelRequirement(80)],
    null,
    null,
    ["Nechryarch"],
    8,
    [],
    0,
    ["Slayer Tower (CKS)"]
  ),
  new Task(
    "Smoke devils",
    93,
    200,
    [new SlayerLevelRequirement(93)],
    null,
    null,
    ["Thermonuclear smoke devil"],
    8,
    [],
    0,
    ["Smoke Devil Dungeon"]
  ),
  new Task(
    "Spiritual creatures",
    63,
    200,
    [new SlayerLevelRequirement(63)],
    null,
    null,
    ["Spiritual ranger", "Spiritual warrior", "Spiritual mage"],
    8,
    [],
    0,
    ["God Wars Dungeon"]
  ),
  new Task(
    "Steel dragons",
    1,
    60,
    [new CombatLevelRequirement(90)],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Brimhaven Dungeon", "Catacombs of Kourend"]
  ),
  new Task(
    "Suqah",
    1,
    60,
    [new QuestRequirement("Lunar Diplomacy")],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Lunar Isle"]
  ),
  new Task(
    "Trolls",
    1,
    60,
    [new CombatLevelRequirement(60)],
    null,
    null,
    ["Mountain Troll", "Ice Troll", "Thrower Troll", "Troll General"],
    8,
    [],
    0,
    ["Death Plateau", "Fremennik Isles"]
  ),
  new Task(
    "TzHaar",
    1,
    60,
    [new CombatLevelRequirement(60)],
    null,
    null,
    ["TzHaar-Ket", "TzHaar-Xil", "TzHaar-Mej", "TzHaar-Hur"],
    8,
    [],
    0,
    ["TzHaar City"]
  ),
  new Task(
    "Warped tortoises",
    56,
    200,
    [new SlayerLevelRequirement(56), new QuestRequirement("Path of Glouphrie")],
    null,
    null,
    [],
    8,
    [],
    0,
    ["Poison Waste Dungeon"]
  )
];

export { duradelTasks };
