import {
  CombatLevelRequirement,
  QuestRequirement,
  SlayerLevelRequirement,
} from '../../Requirement';
import { Task } from '../Task';

const krystiliaTasks: Task[] = [
  new Task(
    'Abyssal demons',
    85,
    120,
    [
      new SlayerLevelRequirement(85),
      new CombatLevelRequirement(85),
      new QuestRequirement('Priest in Peril'),
      new QuestRequirement('Fairytale II - Cure a Queen'),
    ],
    null,
    null,
    ['Abyssal Sire'],
    5,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task('Ankou', 1, 120, [new CombatLevelRequirement(40)], null, null, [], 8, [], 0, [
    'Wilderness Slayer Cave',
  ]),
  new Task(
    'Black demons',
    1,
    120,
    [new CombatLevelRequirement(80)],
    null,
    null,
    ['Demonic gorilla'],
    8,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task(
    'Black dragons',
    1,
    120,
    [new CombatLevelRequirement(80)],
    null,
    null,
    ['King Black Dragon', 'Baby black dragon'],
    8,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task(
    'Bloodveld',
    50,
    120,
    [new SlayerLevelRequirement(50), new CombatLevelRequirement(50)],
    null,
    null,
    ['Mutated Bloodveld'],
    8,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task('Chaos druids', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Dark warriors', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task(
    'Dust devils',
    65,
    120,
    [new SlayerLevelRequirement(65), new QuestRequirement('Desert Treasure')],
    null,
    null,
    [],
    8,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task('Earth warriors', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Fire giants', 1, 120, [new CombatLevelRequirement(65)], null, null, [], 8, [], 0, [
    'Wilderness Slayer Cave',
  ]),
  new Task(
    'Greater demons',
    1,
    120,
    [new CombatLevelRequirement(65)],
    null,
    null,
    ['Skotizo', 'Demonic gorilla'],
    8,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task('Green dragons', 1, 120, [], null, null, ['Baby green dragon'], 8, [], 0, [
    'Wilderness Slayer Cave',
  ]),
  new Task(
    'Hellhounds',
    1,
    120,
    [new CombatLevelRequirement(75)],
    null,
    null,
    ['Cerberus'],
    8,
    [],
    0,
    ['Wilderness Slayer Cave'],
  ),
  new Task('Hill giants', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Ice giants', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Ice warriors', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Lesser demons', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Magic axes', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Mammoths', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Moss giants', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Revenants', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Rogues', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Scorpions', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Skeletons', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task('Spiders', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
  new Task(
    'Spiritual creatures',
    63,
    120,
    [new SlayerLevelRequirement(63)],
    null,
    null,
    ['Spiritual ranger', 'Spiritual warrior', 'Spiritual mage'],
    8,
    [],
    0,
    ['Wilderness God Wars Dungeon'],
  ),
  new Task('Steel dragons', 1, 120, [new CombatLevelRequirement(90)], null, null, [], 8, [], 0, [
    'Wilderness Slayer Cave',
  ]),
  new Task('Werewolves', 1, 120, [], null, null, [], 8, [], 0, ['Wilderness Slayer Cave']),
];

export { krystiliaTasks };
